-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snake_top_snake_top_Pipeline_VITIS_LOOP_85_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    st_body_col_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    st_body_col_ce0 : OUT STD_LOGIC;
    st_body_col_we0 : OUT STD_LOGIC;
    st_body_col_d0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    st_body_row_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    st_body_row_ce0 : OUT STD_LOGIC;
    st_body_row_we0 : OUT STD_LOGIC;
    st_body_row_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    grid_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    grid_ce0 : OUT STD_LOGIC;
    grid_we0 : OUT STD_LOGIC;
    grid_d0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of snake_top_snake_top_Pipeline_VITIS_LOOP_85_3 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln85_fu_97_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln85_fu_109_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln90_1_fu_154_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_44 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal i_3_fu_103_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (1 downto 0);
    signal st_body_col_we0_local : STD_LOGIC;
    signal zext_ln86_1_fu_125_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal st_body_col_ce0_local : STD_LOGIC;
    signal st_body_row_we0_local : STD_LOGIC;
    signal st_body_row_ce0_local : STD_LOGIC;
    signal grid_we0_local : STD_LOGIC;
    signal grid_ce0_local : STD_LOGIC;
    signal zext_ln86_fu_115_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_fu_119_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl_fu_134_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln90_fu_130_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln90_fu_142_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln90_fu_148_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snake_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component snake_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_44_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln85_fu_97_p2 = ap_const_lv1_0)) then 
                    i_fu_44 <= i_3_fu_103_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_44 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln90_fu_148_p2 <= std_logic_vector(unsigned(sub_ln90_fu_142_p2) + unsigned(ap_const_lv8_7));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln85_fu_97_p2)
    begin
        if (((icmp_ln85_fu_97_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_state1, i_fu_44, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_44;
        end if; 
    end process;

    c_fu_119_p2 <= std_logic_vector(signed(ap_const_lv4_A) - signed(zext_ln86_fu_115_p1));
    grid_address0 <= zext_ln90_1_fu_154_p1(9 - 1 downto 0);
    grid_ce0 <= grid_ce0_local;

    grid_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grid_ce0_local <= ap_const_logic_1;
        else 
            grid_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grid_d0 <= ap_const_lv1_1;
    grid_we0 <= grid_we0_local;

    grid_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln85_fu_97_p2)
    begin
        if (((icmp_ln85_fu_97_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grid_we0_local <= ap_const_logic_1;
        else 
            grid_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    i_3_fu_103_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv2_1));
    icmp_ln85_fu_97_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv2_3) else "0";
    p_shl_fu_134_p3 <= (c_fu_119_p2 & ap_const_lv4_0);
    st_body_col_address0 <= zext_ln85_fu_109_p1(9 - 1 downto 0);
    st_body_col_ce0 <= st_body_col_ce0_local;

    st_body_col_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            st_body_col_ce0_local <= ap_const_logic_1;
        else 
            st_body_col_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    st_body_col_d0 <= zext_ln86_1_fu_125_p1;
    st_body_col_we0 <= st_body_col_we0_local;

    st_body_col_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln85_fu_97_p2)
    begin
        if (((icmp_ln85_fu_97_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            st_body_col_we0_local <= ap_const_logic_1;
        else 
            st_body_col_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    st_body_row_address0 <= zext_ln85_fu_109_p1(9 - 1 downto 0);
    st_body_row_ce0 <= st_body_row_ce0_local;

    st_body_row_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            st_body_row_ce0_local <= ap_const_logic_1;
        else 
            st_body_row_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    st_body_row_d0 <= ap_const_lv4_7;
    st_body_row_we0 <= st_body_row_we0_local;

    st_body_row_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln85_fu_97_p2)
    begin
        if (((icmp_ln85_fu_97_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            st_body_row_we0_local <= ap_const_logic_1;
        else 
            st_body_row_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    sub_ln90_fu_142_p2 <= std_logic_vector(unsigned(p_shl_fu_134_p3) - unsigned(zext_ln90_fu_130_p1));
    zext_ln85_fu_109_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_2),64));
    zext_ln86_1_fu_125_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_119_p2),5));
    zext_ln86_fu_115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_2),4));
    zext_ln90_1_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln90_fu_148_p2),64));
    zext_ln90_fu_130_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_119_p2),8));
end behav;
