// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top_snake_top_Pipeline_VITIS_LOOP_85_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        st_body_col_address0,
        st_body_col_ce0,
        st_body_col_we0,
        st_body_col_d0,
        st_body_row_address0,
        st_body_row_ce0,
        st_body_row_we0,
        st_body_row_d0,
        grid_address0,
        grid_ce0,
        grid_we0,
        grid_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] st_body_col_address0;
output   st_body_col_ce0;
output   st_body_col_we0;
output  [4:0] st_body_col_d0;
output  [8:0] st_body_row_address0;
output   st_body_row_ce0;
output   st_body_row_we0;
output  [3:0] st_body_row_d0;
output  [8:0] grid_address0;
output   grid_ce0;
output   grid_we0;
output  [0:0] grid_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln85_fu_97_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln85_fu_109_p1;
wire   [63:0] zext_ln90_1_fu_154_p1;
reg   [1:0] i_fu_44;
wire   [1:0] i_3_fu_103_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_i_2;
reg    st_body_col_we0_local;
wire   [4:0] zext_ln86_1_fu_125_p1;
reg    st_body_col_ce0_local;
reg    st_body_row_we0_local;
reg    st_body_row_ce0_local;
reg    grid_we0_local;
reg    grid_ce0_local;
wire   [3:0] zext_ln86_fu_115_p1;
wire   [3:0] c_fu_119_p2;
wire   [7:0] p_shl_fu_134_p3;
wire   [7:0] zext_ln90_fu_130_p1;
wire   [7:0] sub_ln90_fu_142_p2;
wire   [7:0] add_ln90_fu_148_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_44 = 2'd0;
#0 ap_done_reg = 1'b0;
end

snake_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln85_fu_97_p2 == 1'd0)) begin
            i_fu_44 <= i_3_fu_103_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_44 <= 2'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_97_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_2 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        grid_ce0_local = 1'b1;
    end else begin
        grid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_97_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        grid_we0_local = 1'b1;
    end else begin
        grid_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        st_body_col_ce0_local = 1'b1;
    end else begin
        st_body_col_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_97_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        st_body_col_we0_local = 1'b1;
    end else begin
        st_body_col_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        st_body_row_ce0_local = 1'b1;
    end else begin
        st_body_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_97_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        st_body_row_we0_local = 1'b1;
    end else begin
        st_body_row_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln90_fu_148_p2 = (sub_ln90_fu_142_p2 + 8'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign c_fu_119_p2 = ($signed(4'd10) - $signed(zext_ln86_fu_115_p1));

assign grid_address0 = zext_ln90_1_fu_154_p1;

assign grid_ce0 = grid_ce0_local;

assign grid_d0 = 1'd1;

assign grid_we0 = grid_we0_local;

assign i_3_fu_103_p2 = (ap_sig_allocacmp_i_2 + 2'd1);

assign icmp_ln85_fu_97_p2 = ((ap_sig_allocacmp_i_2 == 2'd3) ? 1'b1 : 1'b0);

assign p_shl_fu_134_p3 = {{c_fu_119_p2}, {4'd0}};

assign st_body_col_address0 = zext_ln85_fu_109_p1;

assign st_body_col_ce0 = st_body_col_ce0_local;

assign st_body_col_d0 = zext_ln86_1_fu_125_p1;

assign st_body_col_we0 = st_body_col_we0_local;

assign st_body_row_address0 = zext_ln85_fu_109_p1;

assign st_body_row_ce0 = st_body_row_ce0_local;

assign st_body_row_d0 = 4'd7;

assign st_body_row_we0 = st_body_row_we0_local;

assign sub_ln90_fu_142_p2 = (p_shl_fu_134_p3 - zext_ln90_fu_130_p1);

assign zext_ln85_fu_109_p1 = ap_sig_allocacmp_i_2;

assign zext_ln86_1_fu_125_p1 = c_fu_119_p2;

assign zext_ln86_fu_115_p1 = ap_sig_allocacmp_i_2;

assign zext_ln90_1_fu_154_p1 = add_ln90_fu_148_p2;

assign zext_ln90_fu_130_p1 = c_fu_119_p2;

endmodule //snake_top_snake_top_Pipeline_VITIS_LOOP_85_3
