// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="snake_top_snake_top,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg225-1,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=13.484250,HLS_SYN_LAT=361,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=392,HLS_SYN_LUT=1907,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hand_x,
        hand_y,
        detected,
        vga_x,
        vga_y,
        vsync,
        rst_n,
        R_out,
        R_out_ap_vld,
        G_out,
        G_out_ap_vld,
        B_out,
        B_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] hand_x;
input  [9:0] hand_y;
input  [0:0] detected;
input  [9:0] vga_x;
input  [9:0] vga_y;
input  [0:0] vsync;
input  [0:0] rst_n;
output  [9:0] R_out;
output   R_out_ap_vld;
output  [9:0] G_out;
output   G_out_ap_vld;
output  [9:0] B_out;
output   B_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg R_out_ap_vld;
reg G_out_ap_vld;
reg B_out_ap_vld;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] st_direction;
reg   [3:0] st_frame_count;
reg   [4:0] st_food_col;
reg   [3:0] st_food_row;
reg   [8:0] grid_address0;
reg    grid_ce0;
reg    grid_we0;
reg   [0:0] grid_d0;
wire   [0:0] grid_q0;
reg   [7:0] st_length;
reg   [0:0] st_game_over;
reg   [0:0] vsync_prev;
reg   [8:0] st_body_col_address0;
reg    st_body_col_ce0;
reg    st_body_col_we0;
reg   [4:0] st_body_col_d0;
wire   [4:0] st_body_col_q0;
reg    st_body_col_ce1;
wire   [4:0] st_body_col_q1;
reg   [8:0] st_body_row_address0;
reg    st_body_row_ce0;
reg    st_body_row_we0;
reg   [3:0] st_body_row_d0;
wire   [3:0] st_body_row_q0;
reg    st_body_row_ce1;
wire   [3:0] st_body_row_q1;
reg   [15:0] lfsr;
wire   [0:0] rst_n_read_read_fu_178_p2;
reg   [0:0] rst_n_read_reg_1282;
reg   [9:0] vga_y_read_reg_1286;
reg   [9:0] vga_x_read_reg_1292;
reg   [4:0] st_food_col_load_reg_1337;
reg   [3:0] st_food_row_load_reg_1347;
reg   [0:0] st_game_over_load_reg_1357;
wire   [0:0] and_ln112_fu_588_p2;
reg   [0:0] and_ln112_reg_1365;
wire   [3:0] add_ln148_fu_775_p2;
wire   [0:0] icmp_ln150_fu_781_p2;
reg   [0:0] icmp_ln150_reg_1386;
wire   [3:0] new_head_row_4_fu_870_p3;
reg   [3:0] new_head_row_4_reg_1390;
wire    ap_CS_fsm_state8;
wire   [4:0] new_head_col_4_fu_910_p3;
reg   [4:0] new_head_col_4_reg_1397;
wire   [0:0] wall_hit_fu_930_p2;
reg   [0:0] wall_hit_reg_1404;
wire   [8:0] zext_ln188_fu_940_p1;
reg   [8:0] zext_ln188_reg_1408;
reg   [8:0] grid_addr_reg_1424;
wire   [0:0] will_eat_fu_1003_p2;
reg   [0:0] will_eat_reg_1429;
wire    ap_CS_fsm_state9;
wire   [0:0] self_hit_fu_1031_p2;
reg   [0:0] self_hit_reg_1433;
wire   [8:0] new_len_fu_1070_p2;
wire   [4:0] cell_col_fu_1123_p4;
reg   [4:0] cell_col_reg_1451;
wire    ap_CS_fsm_state14;
wire   [3:0] cell_row_fu_1132_p4;
reg   [3:0] cell_row_reg_1456;
wire   [0:0] in_grid_fu_1151_p2;
reg   [0:0] in_grid_reg_1461;
wire    grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_ready;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_we0;
wire   [0:0] grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_d0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_ready;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_we0;
wire   [4:0] grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_d0;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_we0;
wire   [3:0] grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_d0;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_we0;
wire   [0:0] grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_d0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_ready;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_we0;
wire   [4:0] grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_d0;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_we0;
wire   [3:0] grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_d0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_ready;
wire   [15:0] grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_or_ln_out;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_or_ln_out_ap_vld;
wire   [3:0] grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_r_5_out;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_r_5_out_ap_vld;
wire   [4:0] grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_c_6_out;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_c_6_out_ap_vld;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_grid_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_grid_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_ready;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_we0;
wire   [4:0] grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_d0;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_address1;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_ce1;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_we0;
wire   [3:0] grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_d0;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_address1;
wire    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_ce1;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_ready;
wire   [15:0] grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_or_ln14_1_out;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_or_ln14_1_out_ap_vld;
wire   [3:0] grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_r_6_out;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_r_6_out_ap_vld;
wire   [4:0] grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_c_7_out;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_c_7_out_ap_vld;
wire   [8:0] grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_grid_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_grid_ce0;
reg   [1:0] st_direction_loc_1_reg_300;
wire   [0:0] detected_read_read_fu_202_p2;
wire   [0:0] and_ln136_fu_709_p2;
wire   [0:0] and_ln137_fu_727_p2;
wire   [0:0] and_ln138_fu_745_p2;
wire   [0:0] reversal_fu_763_p2;
wire   [1:0] new_dir_2_fu_688_p3;
reg   [8:0] new_len_2_reg_318;
reg   [0:0] st_frame_count_flag_0_reg_328;
wire    ap_CS_fsm_state12;
reg   [3:0] st_frame_count_new_0_reg_353;
reg   [4:0] st_food_col_loc_1_reg_377;
reg   [3:0] st_food_row_loc_1_reg_394;
reg   [0:0] empty_13_reg_411;
reg   [0:0] ap_phi_mux_st_frame_count_flag_1_phi_fu_435_p4;
reg   [0:0] st_frame_count_flag_1_reg_431;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state7;
reg   [3:0] ap_phi_mux_st_frame_count_new_1_phi_fu_447_p4;
reg   [3:0] st_frame_count_new_1_reg_443;
wire   [0:0] select_ln243_fu_1222_p3;
reg   [0:0] ap_phi_mux_storemerge2_phi_fu_459_p4;
reg   [0:0] storemerge2_reg_455;
wire   [0:0] xor_ln243_fu_1231_p2;
reg   [0:0] ap_phi_mux_storemerge_phi_fu_470_p4;
reg   [0:0] storemerge_reg_466;
wire   [7:0] select_ln243_1_fu_1244_p3;
reg   [7:0] ap_phi_mux_storemerge1_phi_fu_481_p4;
reg   [7:0] storemerge1_reg_477;
reg    grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    grid_we0_out;
reg    grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    st_body_col_we0_out;
wire    st_body_row_we0_out;
reg    grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start_reg;
reg   [15:0] or_ln_loc_fu_174;
reg   [3:0] r_5_loc_fu_170;
reg   [4:0] c_6_loc_fu_166;
reg    grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start_reg;
wire    ap_CS_fsm_state13;
reg   [15:0] or_ln14_1_loc_fu_162;
reg   [3:0] r_6_loc_fu_158;
reg   [4:0] c_7_loc_fu_154;
wire  signed [63:0] sext_ln188_fu_950_p1;
wire   [63:0] zext_ln191_2_fu_984_p1;
wire   [63:0] zext_ln199_2_fu_1065_p1;
wire   [63:0] zext_ln238_2_fu_1185_p1;
wire   [7:0] trunc_ln213_fu_1081_p1;
reg    st_body_col_ce0_local;
reg   [8:0] st_body_col_address0_local;
reg    st_body_col_we0_local;
reg    st_body_row_ce0_local;
reg   [8:0] st_body_row_address0_local;
reg    st_body_row_we0_local;
reg    grid_ce0_local;
reg   [8:0] grid_address0_local;
reg    grid_we0_local;
reg   [0:0] grid_d0_local;
wire   [0:0] or_ln112_fu_576_p2;
wire   [0:0] xor_ln112_fu_582_p2;
wire   [10:0] zext_ln121_fu_594_p1;
wire   [10:0] zext_ln122_fu_604_p1;
wire   [10:0] dx_fu_598_p2;
wire   [0:0] tmp_fu_614_p3;
wire   [10:0] abs_dx_fu_622_p2;
wire   [10:0] dy_fu_608_p2;
wire   [0:0] tmp_11_fu_636_p3;
wire   [10:0] abs_dy_fu_644_p2;
wire   [10:0] abs_dx_1_fu_628_p3;
wire   [10:0] abs_dy_1_fu_650_p3;
wire   [0:0] icmp_ln130_fu_664_p2;
wire   [0:0] new_dir_1_fu_678_p2;
wire   [0:0] icmp_ln129_fu_658_p2;
wire   [1:0] new_dir_fu_670_p3;
wire   [1:0] zext_ln132_fu_684_p1;
wire   [0:0] icmp_ln136_fu_697_p2;
wire   [0:0] icmp_ln136_1_fu_703_p2;
wire   [0:0] icmp_ln137_fu_715_p2;
wire   [0:0] icmp_ln137_1_fu_721_p2;
wire   [0:0] icmp_ln138_fu_733_p2;
wire   [0:0] icmp_ln138_1_fu_739_p2;
wire   [0:0] icmp_ln139_fu_751_p2;
wire   [0:0] icmp_ln139_1_fu_757_p2;
wire   [0:0] icmp_ln158_fu_838_p2;
wire   [3:0] new_head_row_1_fu_844_p2;
wire   [0:0] icmp_ln160_fu_858_p2;
wire   [3:0] new_head_row_3_fu_864_p2;
wire   [3:0] new_head_row_2_fu_850_p3;
wire   [0:0] icmp_ln162_fu_878_p2;
wire   [4:0] new_head_col_1_fu_884_p2;
wire   [0:0] icmp_ln164_fu_898_p2;
wire   [4:0] new_head_col_3_fu_904_p2;
wire   [4:0] new_head_col_2_fu_890_p3;
wire   [0:0] icmp_ln171_fu_918_p2;
wire   [0:0] icmp_ln172_fu_924_p2;
wire   [8:0] add_ln188_fu_944_p2;
wire   [8:0] p_shl1_fu_960_p3;
wire   [8:0] zext_ln191_fu_956_p1;
wire   [8:0] sub_ln191_fu_968_p2;
wire   [8:0] zext_ln191_1_fu_974_p1;
wire   [8:0] add_ln191_fu_978_p2;
wire   [0:0] icmp_ln180_fu_995_p2;
wire   [0:0] icmp_ln181_fu_999_p2;
wire   [0:0] icmp_ln189_fu_1009_p2;
wire   [0:0] not_icmp_ln188_fu_1014_p2;
wire   [0:0] empty_fu_1019_p2;
wire   [0:0] or_ln192_fu_1025_p2;
wire   [8:0] p_shl2_fu_1041_p3;
wire   [8:0] zext_ln199_fu_1037_p1;
wire   [8:0] sub_ln199_fu_1049_p2;
wire   [8:0] zext_ln199_1_fu_1055_p1;
wire   [8:0] add_ln199_fu_1059_p2;
wire   [0:0] icmp_ln235_fu_1141_p2;
wire   [0:0] icmp_ln236_fu_1146_p2;
wire   [8:0] p_shl_fu_1161_p3;
wire   [8:0] zext_ln238_fu_1157_p1;
wire   [8:0] sub_ln238_fu_1169_p2;
wire   [8:0] zext_ln238_1_fu_1175_p1;
wire   [8:0] add_ln238_fu_1179_p2;
wire   [0:0] is_snake_fu_1190_p2;
wire   [0:0] icmp_ln240_fu_1195_p2;
wire   [0:0] icmp_ln241_fu_1206_p2;
wire   [0:0] and_ln239_fu_1211_p2;
wire   [0:0] or_ln243_fu_1200_p2;
wire   [0:0] and_ln239_1_fu_1217_p2;
wire   [0:0] or_ln243_1_fu_1238_p2;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_block_state6_on_subcall_done;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 st_direction = 2'd0;
#0 st_frame_count = 4'd0;
#0 st_food_col = 5'd0;
#0 st_food_row = 4'd0;
#0 st_length = 8'd0;
#0 st_game_over = 1'd0;
#0 vsync_prev = 1'd0;
#0 lfsr = 16'd0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start_reg = 1'b0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start_reg = 1'b0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start_reg = 1'b0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start_reg = 1'b0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start_reg = 1'b0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start_reg = 1'b0;
end

snake_top_grid_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 300 ),
    .AddressWidth( 9 ))
grid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grid_address0),
    .ce0(grid_ce0),
    .we0(grid_we0),
    .d0(grid_d0),
    .q0(grid_q0)
);

snake_top_st_body_col_RAM_AUTO_1R1W #(
    .DataWidth( 5 ),
    .AddressRange( 300 ),
    .AddressWidth( 9 ))
st_body_col_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st_body_col_address0),
    .ce0(st_body_col_ce0),
    .we0(st_body_col_we0),
    .d0(st_body_col_d0),
    .q0(st_body_col_q0),
    .address1(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_address1),
    .ce1(st_body_col_ce1),
    .q1(st_body_col_q1)
);

snake_top_st_body_row_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 300 ),
    .AddressWidth( 9 ))
st_body_row_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st_body_row_address0),
    .ce0(st_body_row_ce0),
    .we0(st_body_row_we0),
    .d0(st_body_row_d0),
    .q0(st_body_row_q0),
    .address1(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_address1),
    .ce1(st_body_row_ce1),
    .q1(st_body_row_q1)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2 grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_ready),
    .grid_address0(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_address0),
    .grid_ce0(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_ce0),
    .grid_we0(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_we0),
    .grid_d0(grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_d0)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_85_3 grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_ready),
    .st_body_col_address0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_address0),
    .st_body_col_ce0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_ce0),
    .st_body_col_we0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_we0),
    .st_body_col_d0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_d0),
    .st_body_row_address0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_address0),
    .st_body_row_ce0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_ce0),
    .st_body_row_we0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_we0),
    .st_body_row_d0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_d0),
    .grid_address0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_address0),
    .grid_ce0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_ce0),
    .grid_we0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_we0),
    .grid_d0(grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_d0)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_94_4 grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_ready),
    .st_body_col_address0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_address0),
    .st_body_col_ce0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_ce0),
    .st_body_col_we0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_we0),
    .st_body_col_d0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_d0),
    .st_body_row_address0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_address0),
    .st_body_row_ce0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_ce0),
    .st_body_row_we0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_we0),
    .st_body_row_d0(grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_d0)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_27_1 grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_ready),
    .or_ln_out(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_or_ln_out),
    .or_ln_out_ap_vld(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_or_ln_out_ap_vld),
    .r_5_out(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_r_5_out),
    .r_5_out_ap_vld(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_r_5_out_ap_vld),
    .c_6_out(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_c_6_out),
    .c_6_out_ap_vld(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_c_6_out_ap_vld),
    .grid_address0(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_grid_address0),
    .grid_ce0(grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_grid_ce0),
    .grid_q0(grid_q0)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_207_5 grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_ready),
    .new_len_2(new_len_2_reg_318),
    .st_body_col_address0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_address0),
    .st_body_col_ce0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_ce0),
    .st_body_col_we0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_we0),
    .st_body_col_d0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_d0),
    .st_body_col_address1(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_address1),
    .st_body_col_ce1(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_ce1),
    .st_body_col_q1(st_body_col_q1),
    .st_body_row_address0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_address0),
    .st_body_row_ce0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_ce0),
    .st_body_row_we0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_we0),
    .st_body_row_d0(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_d0),
    .st_body_row_address1(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_address1),
    .st_body_row_ce1(grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_ce1),
    .st_body_row_q1(st_body_row_q1)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_27_11 grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_ready),
    .lfsr_load(lfsr),
    .or_ln14_1_out(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_or_ln14_1_out),
    .or_ln14_1_out_ap_vld(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_or_ln14_1_out_ap_vld),
    .r_6_out(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_r_6_out),
    .r_6_out_ap_vld(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_r_6_out_ap_vld),
    .c_7_out(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_c_7_out),
    .c_7_out_ap_vld(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_c_7_out_ap_vld),
    .grid_address0(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_grid_address0),
    .grid_ce0(grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_grid_ce0),
    .grid_q0(grid_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state12) & (will_eat_reg_1429 == 1'd1))) begin
            grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start_reg <= 1'b0;
    end else begin
        if (((rst_n_read_read_fu_178_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state12) & (will_eat_reg_1429 == 1'd0)) | ((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1)))) begin
        empty_13_reg_411 <= st_game_over_load_reg_1357;
    end else if ((((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln150_fu_781_p2 == 1'd0)))) begin
        empty_13_reg_411 <= st_game_over;
    end else if ((((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (wall_hit_fu_930_p2 == 1'd1)))) begin
        empty_13_reg_411 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        lfsr <= or_ln_loc_fu_174;
    end else if (((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1))) begin
        lfsr <= or_ln14_1_loc_fu_162;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd0))) begin
        if ((will_eat_fu_1003_p2 == 1'd0)) begin
            new_len_2_reg_318 <= zext_ln188_reg_1408;
        end else if ((will_eat_fu_1003_p2 == 1'd1)) begin
            new_len_2_reg_318 <= new_len_fu_1070_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln138_fu_745_p2) & (1'd0 == and_ln137_fu_727_p2) & (1'd0 == and_ln136_fu_709_p2) & (reversal_fu_763_p2 == 1'd0) & (detected_read_read_fu_202_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        st_direction <= new_dir_2_fu_688_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        st_direction <= 2'd3;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln138_fu_745_p2) & (1'd0 == and_ln137_fu_727_p2) & (1'd0 == and_ln136_fu_709_p2) & (reversal_fu_763_p2 == 1'd0) & (detected_read_read_fu_202_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        st_direction_loc_1_reg_300 <= new_dir_2_fu_688_p3;
    end else if ((((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln138_fu_745_p2) & (1'd0 == and_ln137_fu_727_p2) & (1'd0 == and_ln136_fu_709_p2) & (reversal_fu_763_p2 == 1'd1) & (detected_read_read_fu_202_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln137_fu_727_p2) & (1'd0 == and_ln136_fu_709_p2) & (detected_read_read_fu_202_p2 == 1'd1) & (1'd1 == and_ln138_fu_745_p2) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln136_fu_709_p2) & (detected_read_read_fu_202_p2 == 1'd1) & (1'd1 == and_ln137_fu_727_p2) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (detected_read_read_fu_202_p2 == 1'd1) & (1'd1 == and_ln136_fu_709_p2) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (detected_read_read_fu_202_p2 
    == 1'd0) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        st_direction_loc_1_reg_300 <= st_direction;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        st_food_col <= c_6_loc_fu_166;
    end else if (((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1))) begin
        st_food_col <= c_7_loc_fu_154;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1))) begin
        st_food_col_loc_1_reg_377 <= c_7_loc_fu_154;
    end else if ((((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln150_fu_781_p2 == 1'd0)))) begin
        st_food_col_loc_1_reg_377 <= st_food_col;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (will_eat_reg_1429 == 1'd0)) | ((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (wall_hit_fu_930_p2 == 1'd1)))) begin
        st_food_col_loc_1_reg_377 <= st_food_col_load_reg_1337;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        st_food_row <= r_5_loc_fu_170;
    end else if (((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1))) begin
        st_food_row <= r_6_loc_fu_158;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1))) begin
        st_food_row_loc_1_reg_394 <= r_6_loc_fu_158;
    end else if ((((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln150_fu_781_p2 == 1'd0)))) begin
        st_food_row_loc_1_reg_394 <= st_food_row;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (will_eat_reg_1429 == 1'd0)) | ((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (wall_hit_fu_930_p2 == 1'd1)))) begin
        st_food_row_loc_1_reg_394 <= st_food_row_load_reg_1347;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        st_frame_count_flag_0_reg_328 <= 1'd0;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (will_eat_reg_1429 == 1'd0)) | ((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln150_fu_781_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (wall_hit_fu_930_p2 == 1'd1)))) begin
        st_frame_count_flag_0_reg_328 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        st_frame_count_flag_1_reg_431 <= 1'd1;
    end else if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        st_frame_count_flag_1_reg_431 <= st_frame_count_flag_0_reg_328;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln150_fu_781_p2 == 1'd0))) begin
        st_frame_count_new_0_reg_353 <= add_ln148_fu_775_p2;
    end else if ((((1'b1 == ap_CS_fsm_state12) & (will_eat_reg_1429 == 1'd0)) | ((1'd1 == and_ln112_reg_1365) & (1'b1 == ap_CS_fsm_state14) & (self_hit_reg_1433 == 1'd0) & (will_eat_reg_1429 == 1'd1) & (wall_hit_reg_1404 == 1'd0) & (icmp_ln150_reg_1386 == 1'd1)) | ((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (wall_hit_fu_930_p2 == 1'd1)))) begin
        st_frame_count_new_0_reg_353 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        st_frame_count_new_1_reg_443 <= 4'd0;
    end else if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        st_frame_count_new_1_reg_443 <= st_frame_count_new_0_reg_353;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        st_game_over <= 1'd0;
    end else if ((((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd1)) | ((1'b1 == ap_CS_fsm_state8) & (wall_hit_fu_930_p2 == 1'd1)))) begin
        st_game_over <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        st_length <= 8'd3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        st_length <= trunc_ln213_fu_1081_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
                storemerge1_reg_477[7] <= 1'b0;
    end else if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                storemerge1_reg_477[7] <= select_ln243_1_fu_1244_p3[7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        storemerge2_reg_455 <= 1'd0;
    end else if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        storemerge2_reg_455 <= select_ln243_fu_1222_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        storemerge_reg_466 <= 1'd0;
    end else if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        storemerge_reg_466 <= xor_ln243_fu_1231_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_178_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        vsync_prev <= vsync;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        vsync_prev <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln112_reg_1365 <= and_ln112_fu_588_p2;
        icmp_ln150_reg_1386 <= icmp_ln150_fu_781_p2;
        rst_n_read_reg_1282 <= rst_n;
        st_food_col_load_reg_1337 <= st_food_col;
        st_food_row_load_reg_1347 <= st_food_row;
        st_game_over_load_reg_1357 <= st_game_over;
        vga_x_read_reg_1292 <= vga_x;
        vga_y_read_reg_1286 <= vga_y;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_c_6_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        c_6_loc_fu_166 <= grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_c_6_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_c_7_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        c_7_loc_fu_154 <= grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_c_7_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        cell_col_reg_1451 <= {{vga_x_read_reg_1292[9:5]}};
        cell_row_reg_1456 <= {{vga_y_read_reg_1286[8:5]}};
        in_grid_reg_1461 <= in_grid_fu_1151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grid_addr_reg_1424 <= zext_ln191_2_fu_984_p1;
        new_head_col_4_reg_1397 <= new_head_col_4_fu_910_p3;
        new_head_row_4_reg_1390 <= new_head_row_4_fu_870_p3;
        wall_hit_reg_1404 <= wall_hit_fu_930_p2;
        zext_ln188_reg_1408[7 : 0] <= zext_ln188_fu_940_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_or_ln14_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        or_ln14_1_loc_fu_162 <= grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_or_ln14_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_or_ln_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        or_ln_loc_fu_174 <= grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_or_ln_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_r_5_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        r_5_loc_fu_170 <= grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_r_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_r_6_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        r_6_loc_fu_158 <= grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_r_6_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        self_hit_reg_1433 <= self_hit_fu_1031_p2;
        will_eat_reg_1429 <= will_eat_fu_1003_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_st_frame_count_flag_1_phi_fu_435_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        st_frame_count <= ap_phi_mux_st_frame_count_new_1_phi_fu_447_p4;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_out_ap_vld = 1'b1;
    end else begin
        B_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        G_out_ap_vld = 1'b1;
    end else begin
        G_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        R_out_ap_vld = 1'b1;
    end else begin
        R_out_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state6_on_subcall_done)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_phi_mux_st_frame_count_flag_1_phi_fu_435_p4 = st_frame_count_flag_0_reg_328;
    end else begin
        ap_phi_mux_st_frame_count_flag_1_phi_fu_435_p4 = st_frame_count_flag_1_reg_431;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_phi_mux_st_frame_count_new_1_phi_fu_447_p4 = st_frame_count_new_0_reg_353;
    end else begin
        ap_phi_mux_st_frame_count_new_1_phi_fu_447_p4 = st_frame_count_new_1_reg_443;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_phi_mux_storemerge1_phi_fu_481_p4 = select_ln243_1_fu_1244_p3;
    end else begin
        ap_phi_mux_storemerge1_phi_fu_481_p4 = storemerge1_reg_477;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_phi_mux_storemerge2_phi_fu_459_p4 = select_ln243_fu_1222_p3;
    end else begin
        ap_phi_mux_storemerge2_phi_fu_459_p4 = storemerge2_reg_455;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1282 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_phi_mux_storemerge_phi_fu_470_p4 = xor_ln243_fu_1231_p2;
    end else begin
        ap_phi_mux_storemerge_phi_fu_470_p4 = storemerge_reg_466;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grid_address0 = grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_grid_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grid_address0 = grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_grid_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_address0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_address0 = grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_address0;
    end else begin
        grid_address0 = grid_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grid_address0_local = zext_ln238_2_fu_1185_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grid_address0_local = grid_addr_reg_1424;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grid_address0_local = zext_ln199_2_fu_1065_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grid_address0_local = zext_ln191_2_fu_984_p1;
    end else begin
        grid_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grid_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_grid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grid_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_grid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_ce0;
    end else begin
        grid_ce0 = grid_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        grid_ce0_local = 1'b1;
    end else begin
        grid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_d0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_d0 = grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_d0;
    end else begin
        grid_d0 = grid_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grid_d0_local = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grid_d0_local = 1'd0;
    end else begin
        grid_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grid_we0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_grid_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grid_we0 = grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_grid_we0;
    end else begin
        grid_we0 = (grid_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd0) & (will_eat_fu_1003_p2 == 1'd0)))) begin
        grid_we0_local = 1'b1;
    end else begin
        grid_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_col_address0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_col_address0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_col_address0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_address0;
    end else begin
        st_body_col_address0 = st_body_col_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st_body_col_address0_local = sext_ln188_fu_950_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state1))) begin
        st_body_col_address0_local = 9'd0;
    end else begin
        st_body_col_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_col_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_col_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_col_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_ce0;
    end else begin
        st_body_col_ce0 = st_body_col_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        st_body_col_ce0_local = 1'b1;
    end else begin
        st_body_col_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_col_ce1 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_ce1;
    end else begin
        st_body_col_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_col_d0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_col_d0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_col_d0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_d0;
    end else begin
        st_body_col_d0 = new_head_col_4_reg_1397;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_col_we0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_col_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_col_we0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_col_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_col_we0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_col_we0;
    end else begin
        st_body_col_we0 = (st_body_col_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        st_body_col_we0_local = 1'b1;
    end else begin
        st_body_col_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_row_address0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_row_address0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_row_address0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_address0;
    end else begin
        st_body_row_address0 = st_body_row_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st_body_row_address0_local = sext_ln188_fu_950_p1;
    end else if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state1))) begin
        st_body_row_address0_local = 9'd0;
    end else begin
        st_body_row_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_row_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_row_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_row_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_ce0;
    end else begin
        st_body_row_ce0 = st_body_row_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        st_body_row_ce0_local = 1'b1;
    end else begin
        st_body_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_row_ce1 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_ce1;
    end else begin
        st_body_row_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_row_d0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_row_d0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_row_d0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_d0;
    end else begin
        st_body_row_d0 = new_head_row_4_reg_1390;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        st_body_row_we0 = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_st_body_row_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st_body_row_we0 = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_st_body_row_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st_body_row_we0 = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_st_body_row_we0;
    end else begin
        st_body_row_we0 = (st_body_row_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        st_body_row_we0_local = 1'b1;
    end else begin
        st_body_row_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd1 == and_ln112_fu_588_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln150_fu_781_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (((rst_n_read_read_fu_178_p2 == 1'd1) & (1'd0 == and_ln112_fu_588_p2)) | ((rst_n_read_read_fu_178_p2 == 1'd1) & (icmp_ln150_fu_781_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((rst_n_read_read_fu_178_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (wall_hit_fu_930_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (self_hit_fu_1031_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (will_eat_reg_1429 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_out = ap_phi_mux_storemerge1_phi_fu_481_p4;

assign G_out = ((ap_phi_mux_storemerge_phi_fu_470_p4[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign R_out = ((ap_phi_mux_storemerge2_phi_fu_459_p4[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign abs_dx_1_fu_628_p3 = ((tmp_fu_614_p3[0:0] == 1'b1) ? abs_dx_fu_622_p2 : dx_fu_598_p2);

assign abs_dx_fu_622_p2 = (11'd320 - zext_ln121_fu_594_p1);

assign abs_dy_1_fu_650_p3 = ((tmp_11_fu_636_p3[0:0] == 1'b1) ? abs_dy_fu_644_p2 : dy_fu_608_p2);

assign abs_dy_fu_644_p2 = (11'd240 - zext_ln122_fu_604_p1);

assign add_ln148_fu_775_p2 = (st_frame_count + 4'd1);

assign add_ln188_fu_944_p2 = ($signed(zext_ln188_fu_940_p1) + $signed(9'd511));

assign add_ln191_fu_978_p2 = (sub_ln191_fu_968_p2 + zext_ln191_1_fu_974_p1);

assign add_ln199_fu_1059_p2 = (sub_ln199_fu_1049_p2 + zext_ln199_1_fu_1055_p1);

assign add_ln238_fu_1179_p2 = (sub_ln238_fu_1169_p2 + zext_ln238_1_fu_1175_p1);

assign and_ln112_fu_588_p2 = (xor_ln112_fu_582_p2 & vsync_prev);

assign and_ln136_fu_709_p2 = (icmp_ln136_fu_697_p2 & icmp_ln136_1_fu_703_p2);

assign and_ln137_fu_727_p2 = (icmp_ln137_fu_715_p2 & icmp_ln137_1_fu_721_p2);

assign and_ln138_fu_745_p2 = (icmp_ln138_fu_733_p2 & icmp_ln138_1_fu_739_p2);

assign and_ln239_1_fu_1217_p2 = (in_grid_reg_1461 & and_ln239_fu_1211_p2);

assign and_ln239_fu_1211_p2 = (icmp_ln241_fu_1206_p2 & icmp_ln240_fu_1195_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_done == 1'b0) | (grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_done == 1'b0));
end

assign cell_col_fu_1123_p4 = {{vga_x_read_reg_1292[9:5]}};

assign cell_row_fu_1132_p4 = {{vga_y_read_reg_1286[8:5]}};

assign detected_read_read_fu_202_p2 = detected;

assign dx_fu_598_p2 = ($signed(zext_ln121_fu_594_p1) + $signed(11'd1728));

assign dy_fu_608_p2 = ($signed(zext_ln122_fu_604_p1) + $signed(11'd1808));

assign empty_fu_1019_p2 = (not_icmp_ln188_fu_1014_p2 | icmp_ln189_fu_1009_p2);

assign grid_we0_out = grid_we0_local;

assign grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_207_5_fu_521_ap_start_reg;

assign grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_27_11_fu_531_ap_start_reg;

assign grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_27_1_fu_512_ap_start_reg;

assign grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_fu_488_ap_start_reg;

assign grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_85_3_fu_494_ap_start_reg;

assign grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_94_4_fu_504_ap_start_reg;

assign icmp_ln129_fu_658_p2 = (($signed(abs_dx_1_fu_628_p3) > $signed(abs_dy_1_fu_650_p3)) ? 1'b1 : 1'b0);

assign icmp_ln130_fu_664_p2 = (($signed(dx_fu_598_p2) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln136_1_fu_703_p2 = ((st_direction == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_697_p2 = ((new_dir_2_fu_688_p3 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln137_1_fu_721_p2 = ((st_direction == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_715_p2 = ((new_dir_2_fu_688_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln138_1_fu_739_p2 = ((st_direction == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_733_p2 = ((new_dir_2_fu_688_p3 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln139_1_fu_757_p2 = ((st_direction == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_751_p2 = ((new_dir_2_fu_688_p3 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln150_fu_781_p2 = ((add_ln148_fu_775_p2 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_838_p2 = ((st_direction_loc_1_reg_300 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln160_fu_858_p2 = ((st_direction_loc_1_reg_300 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_878_p2 = ((st_direction_loc_1_reg_300 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln164_fu_898_p2 = ((st_direction_loc_1_reg_300 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln171_fu_918_p2 = ((new_head_col_4_fu_910_p3 > 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_924_p2 = ((new_head_row_4_fu_870_p3 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_995_p2 = ((new_head_col_4_reg_1397 == st_food_col_load_reg_1337) ? 1'b1 : 1'b0);

assign icmp_ln181_fu_999_p2 = ((new_head_row_4_reg_1390 == st_food_row_load_reg_1347) ? 1'b1 : 1'b0);

assign icmp_ln189_fu_1009_p2 = ((new_head_row_4_reg_1390 != st_body_row_q0) ? 1'b1 : 1'b0);

assign icmp_ln235_fu_1141_p2 = ((vga_x_read_reg_1292 < 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln236_fu_1146_p2 = ((vga_y_read_reg_1286 < 10'd480) ? 1'b1 : 1'b0);

assign icmp_ln240_fu_1195_p2 = ((cell_col_reg_1451 == st_food_col_loc_1_reg_377) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_1206_p2 = ((cell_row_reg_1456 == st_food_row_loc_1_reg_394) ? 1'b1 : 1'b0);

assign in_grid_fu_1151_p2 = (icmp_ln236_fu_1146_p2 & icmp_ln235_fu_1141_p2);

assign is_snake_fu_1190_p2 = (in_grid_reg_1461 & grid_q0);

assign new_dir_1_fu_678_p2 = (($signed(dy_fu_608_p2) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign new_dir_2_fu_688_p3 = ((icmp_ln129_fu_658_p2[0:0] == 1'b1) ? new_dir_fu_670_p3 : zext_ln132_fu_684_p1);

assign new_dir_fu_670_p3 = ((icmp_ln130_fu_664_p2[0:0] == 1'b1) ? 2'd3 : 2'd2);

assign new_head_col_1_fu_884_p2 = ($signed(st_body_col_q0) + $signed(5'd31));

assign new_head_col_2_fu_890_p3 = ((icmp_ln162_fu_878_p2[0:0] == 1'b1) ? new_head_col_1_fu_884_p2 : st_body_col_q0);

assign new_head_col_3_fu_904_p2 = (st_body_col_q0 + 5'd1);

assign new_head_col_4_fu_910_p3 = ((icmp_ln164_fu_898_p2[0:0] == 1'b1) ? new_head_col_3_fu_904_p2 : new_head_col_2_fu_890_p3);

assign new_head_row_1_fu_844_p2 = ($signed(st_body_row_q0) + $signed(4'd15));

assign new_head_row_2_fu_850_p3 = ((icmp_ln158_fu_838_p2[0:0] == 1'b1) ? new_head_row_1_fu_844_p2 : st_body_row_q0);

assign new_head_row_3_fu_864_p2 = (st_body_row_q0 + 4'd1);

assign new_head_row_4_fu_870_p3 = ((icmp_ln160_fu_858_p2[0:0] == 1'b1) ? new_head_row_3_fu_864_p2 : new_head_row_2_fu_850_p3);

assign new_len_fu_1070_p2 = (zext_ln188_reg_1408 + 9'd1);

assign not_icmp_ln188_fu_1014_p2 = ((new_head_col_4_reg_1397 != st_body_col_q0) ? 1'b1 : 1'b0);

assign or_ln112_fu_576_p2 = (vsync | st_game_over);

assign or_ln192_fu_1025_p2 = (will_eat_fu_1003_p2 | empty_fu_1019_p2);

assign or_ln243_1_fu_1238_p2 = (or_ln243_fu_1200_p2 | and_ln239_1_fu_1217_p2);

assign or_ln243_fu_1200_p2 = (is_snake_fu_1190_p2 | empty_13_reg_411);

assign p_shl1_fu_960_p3 = {{new_head_col_4_fu_910_p3}, {4'd0}};

assign p_shl2_fu_1041_p3 = {{st_body_col_q0}, {4'd0}};

assign p_shl_fu_1161_p3 = {{cell_col_fu_1123_p4}, {4'd0}};

assign reversal_fu_763_p2 = (icmp_ln139_fu_751_p2 & icmp_ln139_1_fu_757_p2);

assign rst_n_read_read_fu_178_p2 = rst_n;

assign select_ln243_1_fu_1244_p3 = ((or_ln243_1_fu_1238_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign select_ln243_fu_1222_p3 = ((or_ln243_fu_1200_p2[0:0] == 1'b1) ? empty_13_reg_411 : and_ln239_1_fu_1217_p2);

assign self_hit_fu_1031_p2 = (or_ln192_fu_1025_p2 & grid_q0);

assign sext_ln188_fu_950_p1 = $signed(add_ln188_fu_944_p2);

assign st_body_col_we0_out = st_body_col_we0_local;

assign st_body_row_we0_out = st_body_row_we0_local;

assign sub_ln191_fu_968_p2 = (p_shl1_fu_960_p3 - zext_ln191_fu_956_p1);

assign sub_ln199_fu_1049_p2 = (p_shl2_fu_1041_p3 - zext_ln199_fu_1037_p1);

assign sub_ln238_fu_1169_p2 = (p_shl_fu_1161_p3 - zext_ln238_fu_1157_p1);

assign tmp_11_fu_636_p3 = dy_fu_608_p2[32'd10];

assign tmp_fu_614_p3 = dx_fu_598_p2[32'd10];

assign trunc_ln213_fu_1081_p1 = new_len_2_reg_318[7:0];

assign wall_hit_fu_930_p2 = (icmp_ln172_fu_924_p2 | icmp_ln171_fu_918_p2);

assign will_eat_fu_1003_p2 = (icmp_ln181_fu_999_p2 & icmp_ln180_fu_995_p2);

assign xor_ln112_fu_582_p2 = (or_ln112_fu_576_p2 ^ 1'd1);

assign xor_ln243_fu_1231_p2 = (or_ln243_fu_1200_p2 ^ empty_13_reg_411);

assign zext_ln121_fu_594_p1 = hand_x;

assign zext_ln122_fu_604_p1 = hand_y;

assign zext_ln132_fu_684_p1 = new_dir_1_fu_678_p2;

assign zext_ln188_fu_940_p1 = st_length;

assign zext_ln191_1_fu_974_p1 = new_head_row_4_fu_870_p3;

assign zext_ln191_2_fu_984_p1 = add_ln191_fu_978_p2;

assign zext_ln191_fu_956_p1 = new_head_col_4_fu_910_p3;

assign zext_ln199_1_fu_1055_p1 = st_body_row_q0;

assign zext_ln199_2_fu_1065_p1 = add_ln199_fu_1059_p2;

assign zext_ln199_fu_1037_p1 = st_body_col_q0;

assign zext_ln238_1_fu_1175_p1 = cell_row_fu_1132_p4;

assign zext_ln238_2_fu_1185_p1 = add_ln238_fu_1179_p2;

assign zext_ln238_fu_1157_p1 = cell_col_fu_1123_p4;

always @ (posedge ap_clk) begin
    zext_ln188_reg_1408[8] <= 1'b0;
    storemerge1_reg_477[6:0] <= 7'b0000000;
end

endmodule //snake_top
