// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top_snake_top_Pipeline_VITIS_LOOP_27_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        lfsr_load,
        or_ln14_1_out,
        or_ln14_1_out_ap_vld,
        r_6_out,
        r_6_out_ap_vld,
        c_7_out,
        c_7_out_ap_vld,
        grid_address0,
        grid_ce0,
        grid_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] lfsr_load;
output  [15:0] or_ln14_1_out;
output   or_ln14_1_out_ap_vld;
output  [3:0] r_6_out;
output   r_6_out_ap_vld;
output  [4:0] c_7_out;
output   c_7_out_ap_vld;
output  [8:0] grid_address0;
output   grid_ce0;
input  [0:0] grid_q0;

reg ap_idle;
reg or_ln14_1_out_ap_vld;
reg r_6_out_ap_vld;
reg c_7_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] or_cond5_i63_fu_380_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [14:0] lshr_ln14_1_reg_434;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_4_reg_439;
wire   [4:0] c_fu_245_p4;
reg   [4:0] c_reg_444;
wire   [3:0] r_fu_255_p4;
reg   [3:0] r_reg_450;
wire   [63:0] zext_ln31_2_fu_293_p1;
wire    ap_block_pp0_stage0;
reg   [4:0] attempt_fu_82;
wire   [4:0] trunc_ln27_fu_362_p1;
wire    ap_loop_init;
reg   [15:0] s_fu_86;
wire   [15:0] or_ln14_1_fu_311_p3;
reg   [15:0] ap_sig_allocacmp_s_1;
reg   [4:0] conv2_i_i186_i37_fu_90;
wire   [4:0] c_1_fu_348_p3;
reg   [3:0] conv2_i_i8_i36_fu_94;
wire   [3:0] r_1_fu_340_p3;
wire    ap_block_pp0_stage0_01001;
reg    grid_ce0_local;
wire   [0:0] tmp_fu_161_p3;
wire   [0:0] tmp_2_fu_177_p3;
wire   [0:0] xor_ln14_fu_195_p2;
wire   [0:0] tmp_1_fu_169_p3;
wire   [0:0] xor_ln14_2_fu_201_p2;
wire   [0:0] tmp_3_fu_215_p3;
wire   [15:0] shl_ln14_1_fu_207_p3;
wire   [15:0] and_ln14_1_fu_223_p3;
wire   [15:0] xor_ln14_1_fu_231_p2;
wire   [8:0] p_shl_fu_269_p3;
wire   [8:0] zext_ln31_fu_265_p1;
wire   [8:0] sub_ln31_fu_277_p2;
wire   [8:0] zext_ln31_1_fu_283_p1;
wire   [8:0] add_ln31_fu_287_p2;
wire   [0:0] icmp_ln31_1_fu_323_p2;
wire   [0:0] or_ln31_fu_328_p2;
wire   [0:0] icmp_ln31_fu_318_p2;
wire   [0:0] or_ln31_1_fu_334_p2;
wire   [5:0] zext_ln27_fu_307_p1;
wire   [5:0] attempt_2_fu_356_p2;
wire   [0:0] tmp_5_fu_366_p3;
wire   [0:0] xor_ln27_fu_374_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 attempt_fu_82 = 5'd0;
#0 s_fu_86 = 16'd0;
#0 conv2_i_i186_i37_fu_90 = 5'd0;
#0 conv2_i_i8_i36_fu_94 = 4'd0;
#0 ap_done_reg = 1'b0;
end

snake_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            attempt_fu_82 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            attempt_fu_82 <= trunc_ln27_fu_362_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            conv2_i_i186_i37_fu_90 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            conv2_i_i186_i37_fu_90 <= c_1_fu_348_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            conv2_i_i8_i36_fu_94 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            conv2_i_i8_i36_fu_94 <= r_1_fu_340_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s_fu_86 <= lfsr_load;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            s_fu_86 <= or_ln14_1_fu_311_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_reg_444 <= {{ap_sig_allocacmp_s_1[5:1]}};
        lshr_ln14_1_reg_434 <= {{ap_sig_allocacmp_s_1[15:1]}};
        r_reg_450 <= {{ap_sig_allocacmp_s_1[9:6]}};
        tmp_4_reg_439 <= xor_ln14_1_fu_231_p2[32'd15];
    end
end

always @ (*) begin
    if (((or_cond5_i63_fu_380_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_s_1 = lfsr_load;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_s_1 = or_ln14_1_fu_311_p3;
        end else begin
            ap_sig_allocacmp_s_1 = s_fu_86;
        end
    end else begin
        ap_sig_allocacmp_s_1 = s_fu_86;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond5_i63_fu_380_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_7_out_ap_vld = 1'b1;
    end else begin
        c_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grid_ce0_local = 1'b1;
    end else begin
        grid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond5_i63_fu_380_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln14_1_out_ap_vld = 1'b1;
    end else begin
        or_ln14_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond5_i63_fu_380_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_6_out_ap_vld = 1'b1;
    end else begin
        r_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_fu_287_p2 = (sub_ln31_fu_277_p2 + zext_ln31_1_fu_283_p1);

assign and_ln14_1_fu_223_p3 = {{tmp_3_fu_215_p3}, {15'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign attempt_2_fu_356_p2 = (zext_ln27_fu_307_p1 + 6'd1);

assign c_1_fu_348_p3 = ((or_ln31_1_fu_334_p2[0:0] == 1'b1) ? conv2_i_i186_i37_fu_90 : c_reg_444);

assign c_7_out = ((or_ln31_1_fu_334_p2[0:0] == 1'b1) ? conv2_i_i186_i37_fu_90 : c_reg_444);

assign c_fu_245_p4 = {{ap_sig_allocacmp_s_1[5:1]}};

assign grid_address0 = zext_ln31_2_fu_293_p1;

assign grid_ce0 = grid_ce0_local;

assign icmp_ln31_1_fu_323_p2 = ((r_reg_450 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_318_p2 = ((c_reg_444 > 5'd19) ? 1'b1 : 1'b0);

assign or_cond5_i63_fu_380_p2 = (xor_ln27_fu_374_p2 & or_ln31_1_fu_334_p2);

assign or_ln14_1_fu_311_p3 = {{tmp_4_reg_439}, {lshr_ln14_1_reg_434}};

assign or_ln14_1_out = {{tmp_4_reg_439}, {lshr_ln14_1_reg_434}};

assign or_ln31_1_fu_334_p2 = (or_ln31_fu_328_p2 | icmp_ln31_fu_318_p2);

assign or_ln31_fu_328_p2 = (icmp_ln31_1_fu_323_p2 | grid_q0);

assign p_shl_fu_269_p3 = {{c_fu_245_p4}, {4'd0}};

assign r_1_fu_340_p3 = ((or_ln31_1_fu_334_p2[0:0] == 1'b1) ? conv2_i_i8_i36_fu_94 : r_reg_450);

assign r_6_out = ((or_ln31_1_fu_334_p2[0:0] == 1'b1) ? conv2_i_i8_i36_fu_94 : r_reg_450);

assign r_fu_255_p4 = {{ap_sig_allocacmp_s_1[9:6]}};

assign shl_ln14_1_fu_207_p3 = {{xor_ln14_2_fu_201_p2}, {15'd0}};

assign sub_ln31_fu_277_p2 = (p_shl_fu_269_p3 - zext_ln31_fu_265_p1);

assign tmp_1_fu_169_p3 = ap_sig_allocacmp_s_1[32'd3];

assign tmp_2_fu_177_p3 = ap_sig_allocacmp_s_1[32'd14];

assign tmp_3_fu_215_p3 = ap_sig_allocacmp_s_1[32'd15];

assign tmp_5_fu_366_p3 = attempt_2_fu_356_p2[32'd5];

assign tmp_fu_161_p3 = ap_sig_allocacmp_s_1[32'd12];

assign trunc_ln27_fu_362_p1 = attempt_2_fu_356_p2[4:0];

assign xor_ln14_1_fu_231_p2 = (shl_ln14_1_fu_207_p3 ^ and_ln14_1_fu_223_p3);

assign xor_ln14_2_fu_201_p2 = (xor_ln14_fu_195_p2 ^ tmp_1_fu_169_p3);

assign xor_ln14_fu_195_p2 = (tmp_fu_161_p3 ^ tmp_2_fu_177_p3);

assign xor_ln27_fu_374_p2 = (tmp_5_fu_366_p3 ^ 1'd1);

assign zext_ln27_fu_307_p1 = attempt_fu_82;

assign zext_ln31_1_fu_283_p1 = r_fu_255_p4;

assign zext_ln31_2_fu_293_p1 = add_ln31_fu_287_p2;

assign zext_ln31_fu_265_p1 = c_fu_245_p4;

endmodule //snake_top_snake_top_Pipeline_VITIS_LOOP_27_11
