// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top_snake_top_Pipeline_VITIS_LOOP_27_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        or_ln_out,
        or_ln_out_ap_vld,
        r_5_out,
        r_5_out_ap_vld,
        c_6_out,
        c_6_out_ap_vld,
        grid_address0,
        grid_ce0,
        grid_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] or_ln_out;
output   or_ln_out_ap_vld;
output  [3:0] r_5_out;
output   r_5_out_ap_vld;
output  [4:0] c_6_out;
output   c_6_out_ap_vld;
output  [8:0] grid_address0;
output   grid_ce0;
input  [0:0] grid_q0;

reg ap_idle;
reg or_ln_out_ap_vld;
reg r_5_out_ap_vld;
reg c_6_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] or_cond5_i_fu_372_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [14:0] lshr_ln_reg_426;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_9_reg_431;
wire   [4:0] c_fu_237_p4;
reg   [4:0] c_reg_436;
wire   [3:0] r_1_fu_247_p4;
reg   [3:0] r_1_reg_442;
wire   [63:0] zext_ln31_4_fu_285_p1;
wire    ap_block_pp0_stage0;
reg   [4:0] attempt_fu_80;
wire   [4:0] trunc_ln27_fu_354_p1;
wire    ap_loop_init;
reg   [15:0] s_fu_84;
wire   [15:0] or_ln_fu_303_p3;
reg   [15:0] ap_sig_allocacmp_s_2;
reg   [4:0] conv2_i_i186_i_fu_88;
wire   [4:0] c_2_fu_340_p3;
reg   [3:0] conv2_i_i8_i_fu_92;
wire   [3:0] r_fu_332_p3;
wire    ap_block_pp0_stage0_01001;
reg    grid_ce0_local;
wire   [0:0] tmp_fu_153_p3;
wire   [0:0] tmp_7_fu_169_p3;
wire   [0:0] xor_ln14_3_fu_187_p2;
wire   [0:0] tmp_6_fu_161_p3;
wire   [0:0] xor_ln14_2_fu_193_p2;
wire   [0:0] tmp_8_fu_207_p3;
wire   [15:0] shl_ln_fu_199_p3;
wire   [15:0] and_ln_fu_215_p3;
wire   [15:0] xor_ln14_fu_223_p2;
wire   [8:0] p_shl_fu_261_p3;
wire   [8:0] zext_ln31_fu_257_p1;
wire   [8:0] sub_ln31_fu_269_p2;
wire   [8:0] zext_ln31_3_fu_275_p1;
wire   [8:0] add_ln31_fu_279_p2;
wire   [0:0] icmp_ln31_1_fu_315_p2;
wire   [0:0] or_ln31_fu_320_p2;
wire   [0:0] icmp_ln31_fu_310_p2;
wire   [0:0] or_ln31_1_fu_326_p2;
wire   [5:0] zext_ln27_fu_299_p1;
wire   [5:0] attempt_4_fu_348_p2;
wire   [0:0] tmp_10_fu_358_p3;
wire   [0:0] xor_ln27_fu_366_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 attempt_fu_80 = 5'd0;
#0 s_fu_84 = 16'd0;
#0 conv2_i_i186_i_fu_88 = 5'd0;
#0 conv2_i_i8_i_fu_92 = 4'd0;
#0 ap_done_reg = 1'b0;
end

snake_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            attempt_fu_80 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            attempt_fu_80 <= trunc_ln27_fu_354_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            conv2_i_i186_i_fu_88 <= 5'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            conv2_i_i186_i_fu_88 <= c_2_fu_340_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            conv2_i_i8_i_fu_92 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            conv2_i_i8_i_fu_92 <= r_fu_332_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s_fu_84 <= 16'd44257;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            s_fu_84 <= or_ln_fu_303_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_reg_436 <= {{ap_sig_allocacmp_s_2[5:1]}};
        lshr_ln_reg_426 <= {{ap_sig_allocacmp_s_2[15:1]}};
        r_1_reg_442 <= {{ap_sig_allocacmp_s_2[9:6]}};
        tmp_9_reg_431 <= xor_ln14_fu_223_p2[32'd15];
    end
end

always @ (*) begin
    if (((or_cond5_i_fu_372_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_s_2 = 16'd44257;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_s_2 = or_ln_fu_303_p3;
        end else begin
            ap_sig_allocacmp_s_2 = s_fu_84;
        end
    end else begin
        ap_sig_allocacmp_s_2 = s_fu_84;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond5_i_fu_372_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_6_out_ap_vld = 1'b1;
    end else begin
        c_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grid_ce0_local = 1'b1;
    end else begin
        grid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond5_i_fu_372_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln_out_ap_vld = 1'b1;
    end else begin
        or_ln_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (or_cond5_i_fu_372_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_5_out_ap_vld = 1'b1;
    end else begin
        r_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln31_fu_279_p2 = (sub_ln31_fu_269_p2 + zext_ln31_3_fu_275_p1);

assign and_ln_fu_215_p3 = {{tmp_8_fu_207_p3}, {15'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign attempt_4_fu_348_p2 = (zext_ln27_fu_299_p1 + 6'd1);

assign c_2_fu_340_p3 = ((or_ln31_1_fu_326_p2[0:0] == 1'b1) ? conv2_i_i186_i_fu_88 : c_reg_436);

assign c_6_out = ((or_ln31_1_fu_326_p2[0:0] == 1'b1) ? conv2_i_i186_i_fu_88 : c_reg_436);

assign c_fu_237_p4 = {{ap_sig_allocacmp_s_2[5:1]}};

assign grid_address0 = zext_ln31_4_fu_285_p1;

assign grid_ce0 = grid_ce0_local;

assign icmp_ln31_1_fu_315_p2 = ((r_1_reg_442 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_310_p2 = ((c_reg_436 > 5'd19) ? 1'b1 : 1'b0);

assign or_cond5_i_fu_372_p2 = (xor_ln27_fu_366_p2 & or_ln31_1_fu_326_p2);

assign or_ln31_1_fu_326_p2 = (or_ln31_fu_320_p2 | icmp_ln31_fu_310_p2);

assign or_ln31_fu_320_p2 = (icmp_ln31_1_fu_315_p2 | grid_q0);

assign or_ln_fu_303_p3 = {{tmp_9_reg_431}, {lshr_ln_reg_426}};

assign or_ln_out = {{tmp_9_reg_431}, {lshr_ln_reg_426}};

assign p_shl_fu_261_p3 = {{c_fu_237_p4}, {4'd0}};

assign r_1_fu_247_p4 = {{ap_sig_allocacmp_s_2[9:6]}};

assign r_5_out = ((or_ln31_1_fu_326_p2[0:0] == 1'b1) ? conv2_i_i8_i_fu_92 : r_1_reg_442);

assign r_fu_332_p3 = ((or_ln31_1_fu_326_p2[0:0] == 1'b1) ? conv2_i_i8_i_fu_92 : r_1_reg_442);

assign shl_ln_fu_199_p3 = {{xor_ln14_2_fu_193_p2}, {15'd0}};

assign sub_ln31_fu_269_p2 = (p_shl_fu_261_p3 - zext_ln31_fu_257_p1);

assign tmp_10_fu_358_p3 = attempt_4_fu_348_p2[32'd5];

assign tmp_6_fu_161_p3 = ap_sig_allocacmp_s_2[32'd3];

assign tmp_7_fu_169_p3 = ap_sig_allocacmp_s_2[32'd14];

assign tmp_8_fu_207_p3 = ap_sig_allocacmp_s_2[32'd15];

assign tmp_fu_153_p3 = ap_sig_allocacmp_s_2[32'd12];

assign trunc_ln27_fu_354_p1 = attempt_4_fu_348_p2[4:0];

assign xor_ln14_2_fu_193_p2 = (xor_ln14_3_fu_187_p2 ^ tmp_6_fu_161_p3);

assign xor_ln14_3_fu_187_p2 = (tmp_fu_153_p3 ^ tmp_7_fu_169_p3);

assign xor_ln14_fu_223_p2 = (shl_ln_fu_199_p3 ^ and_ln_fu_215_p3);

assign xor_ln27_fu_366_p2 = (tmp_10_fu_358_p3 ^ 1'd1);

assign zext_ln27_fu_299_p1 = attempt_fu_80;

assign zext_ln31_3_fu_275_p1 = r_1_fu_247_p4;

assign zext_ln31_4_fu_285_p1 = add_ln31_fu_279_p2;

assign zext_ln31_fu_257_p1 = c_fu_237_p4;

endmodule //snake_top_snake_top_Pipeline_VITIS_LOOP_27_1
