[hls]
relative_roots=C:/Users/aniko/OneDrive/Desktop/ECE554/capstone/snake_hls/snake_hls
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=snake_top/VITIS_LOOP_74_2 
syn.directive.pipeline=snake_top/VITIS_LOOP_85_3 
syn.directive.pipeline=snake_top/VITIS_LOOP_94_4 
syn.directive.pipeline=snake_top/VITIS_LOOP_27_1 
syn.directive.pipeline=snake_top/VITIS_LOOP_207_5 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=snake_top/VITIS_LOOP_73_1  


