-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snake_top_snake_top_Pipeline_VITIS_LOOP_27_11 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    lfsr_load : IN STD_LOGIC_VECTOR (15 downto 0);
    or_ln14_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    or_ln14_1_out_ap_vld : OUT STD_LOGIC;
    r_6_out : OUT STD_LOGIC_VECTOR (3 downto 0);
    r_6_out_ap_vld : OUT STD_LOGIC;
    c_7_out : OUT STD_LOGIC_VECTOR (4 downto 0);
    c_7_out_ap_vld : OUT STD_LOGIC;
    grid_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    grid_ce0 : OUT STD_LOGIC;
    grid_q0 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of snake_top_snake_top_Pipeline_VITIS_LOOP_27_11 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal or_cond5_i63_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal lshr_ln14_1_reg_434 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_4_reg_439 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_245_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal c_reg_444 : STD_LOGIC_VECTOR (4 downto 0);
    signal r_fu_255_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_reg_450 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln31_2_fu_293_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal attempt_fu_82 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal trunc_ln27_fu_362_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal s_fu_86 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal or_ln14_1_fu_311_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_s_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal conv2_i_i186_i37_fu_90 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal c_1_fu_348_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i8_i36_fu_94 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal r_1_fu_340_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grid_ce0_local : STD_LOGIC;
    signal tmp_fu_161_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_177_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln14_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_169_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln14_2_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_215_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln14_1_fu_207_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln14_1_fu_223_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal xor_ln14_1_fu_231_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl_fu_269_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln31_fu_265_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln31_fu_277_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln31_1_fu_283_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln31_fu_287_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln31_1_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln31_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln31_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln31_1_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln27_fu_307_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal attempt_2_fu_356_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_fu_366_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln27_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snake_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component snake_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    attempt_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    attempt_fu_82 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    attempt_fu_82 <= trunc_ln27_fu_362_p1;
                end if;
            end if; 
        end if;
    end process;

    conv2_i_i186_i37_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    conv2_i_i186_i37_fu_90 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    conv2_i_i186_i37_fu_90 <= c_1_fu_348_p3;
                end if;
            end if; 
        end if;
    end process;

    conv2_i_i8_i36_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    conv2_i_i8_i36_fu_94 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    conv2_i_i8_i36_fu_94 <= r_1_fu_340_p3;
                end if;
            end if; 
        end if;
    end process;

    s_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    s_fu_86 <= lfsr_load;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    s_fu_86 <= or_ln14_1_fu_311_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                c_reg_444 <= ap_sig_allocacmp_s_1(5 downto 1);
                lshr_ln14_1_reg_434 <= ap_sig_allocacmp_s_1(15 downto 1);
                r_reg_450 <= ap_sig_allocacmp_s_1(9 downto 6);
                tmp_4_reg_439 <= xor_ln14_1_fu_231_p2(15 downto 15);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln31_fu_287_p2 <= std_logic_vector(unsigned(sub_ln31_fu_277_p2) + unsigned(zext_ln31_1_fu_283_p1));
    and_ln14_1_fu_223_p3 <= (tmp_3_fu_215_p3 & ap_const_lv15_0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, or_cond5_i63_fu_380_p2)
    begin
        if (((or_cond5_i63_fu_380_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_s_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, lfsr_load, ap_block_pp0_stage0, ap_loop_init, s_fu_86, or_ln14_1_fu_311_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
            if ((ap_loop_init = ap_const_logic_1)) then 
                ap_sig_allocacmp_s_1 <= lfsr_load;
            elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                ap_sig_allocacmp_s_1 <= or_ln14_1_fu_311_p3;
            else 
                ap_sig_allocacmp_s_1 <= s_fu_86;
            end if;
        else 
            ap_sig_allocacmp_s_1 <= s_fu_86;
        end if; 
    end process;

    attempt_2_fu_356_p2 <= std_logic_vector(unsigned(zext_ln27_fu_307_p1) + unsigned(ap_const_lv6_1));
    c_1_fu_348_p3 <= 
        conv2_i_i186_i37_fu_90 when (or_ln31_1_fu_334_p2(0) = '1') else 
        c_reg_444;
    c_7_out <= 
        conv2_i_i186_i37_fu_90 when (or_ln31_1_fu_334_p2(0) = '1') else 
        c_reg_444;

    c_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_cond5_i63_fu_380_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (or_cond5_i63_fu_380_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            c_7_out_ap_vld <= ap_const_logic_1;
        else 
            c_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    c_fu_245_p4 <= ap_sig_allocacmp_s_1(5 downto 1);
    grid_address0 <= zext_ln31_2_fu_293_p1(9 - 1 downto 0);
    grid_ce0 <= grid_ce0_local;

    grid_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grid_ce0_local <= ap_const_logic_1;
        else 
            grid_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln31_1_fu_323_p2 <= "1" when (r_reg_450 = ap_const_lv4_F) else "0";
    icmp_ln31_fu_318_p2 <= "1" when (unsigned(c_reg_444) > unsigned(ap_const_lv5_13)) else "0";
    or_cond5_i63_fu_380_p2 <= (xor_ln27_fu_374_p2 and or_ln31_1_fu_334_p2);
    or_ln14_1_fu_311_p3 <= (tmp_4_reg_439 & lshr_ln14_1_reg_434);
    or_ln14_1_out <= (tmp_4_reg_439 & lshr_ln14_1_reg_434);

    or_ln14_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_cond5_i63_fu_380_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (or_cond5_i63_fu_380_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            or_ln14_1_out_ap_vld <= ap_const_logic_1;
        else 
            or_ln14_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    or_ln31_1_fu_334_p2 <= (or_ln31_fu_328_p2 or icmp_ln31_fu_318_p2);
    or_ln31_fu_328_p2 <= (icmp_ln31_1_fu_323_p2 or grid_q0);
    p_shl_fu_269_p3 <= (c_fu_245_p4 & ap_const_lv4_0);
    r_1_fu_340_p3 <= 
        conv2_i_i8_i36_fu_94 when (or_ln31_1_fu_334_p2(0) = '1') else 
        r_reg_450;
    r_6_out <= 
        conv2_i_i8_i36_fu_94 when (or_ln31_1_fu_334_p2(0) = '1') else 
        r_reg_450;

    r_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, or_cond5_i63_fu_380_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (or_cond5_i63_fu_380_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            r_6_out_ap_vld <= ap_const_logic_1;
        else 
            r_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    r_fu_255_p4 <= ap_sig_allocacmp_s_1(9 downto 6);
    shl_ln14_1_fu_207_p3 <= (xor_ln14_2_fu_201_p2 & ap_const_lv15_0);
    sub_ln31_fu_277_p2 <= std_logic_vector(unsigned(p_shl_fu_269_p3) - unsigned(zext_ln31_fu_265_p1));
    tmp_1_fu_169_p3 <= ap_sig_allocacmp_s_1(3 downto 3);
    tmp_2_fu_177_p3 <= ap_sig_allocacmp_s_1(14 downto 14);
    tmp_3_fu_215_p3 <= ap_sig_allocacmp_s_1(15 downto 15);
    tmp_5_fu_366_p3 <= attempt_2_fu_356_p2(5 downto 5);
    tmp_fu_161_p3 <= ap_sig_allocacmp_s_1(12 downto 12);
    trunc_ln27_fu_362_p1 <= attempt_2_fu_356_p2(5 - 1 downto 0);
    xor_ln14_1_fu_231_p2 <= (shl_ln14_1_fu_207_p3 xor and_ln14_1_fu_223_p3);
    xor_ln14_2_fu_201_p2 <= (xor_ln14_fu_195_p2 xor tmp_1_fu_169_p3);
    xor_ln14_fu_195_p2 <= (tmp_fu_161_p3 xor tmp_2_fu_177_p3);
    xor_ln27_fu_374_p2 <= (tmp_5_fu_366_p3 xor ap_const_lv1_1);
    zext_ln27_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(attempt_fu_82),6));
    zext_ln31_1_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_fu_255_p4),9));
    zext_ln31_2_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln31_fu_287_p2),64));
    zext_ln31_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_fu_245_p4),9));
end behav;
