// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="snake_top_snake_top,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7z010-clg225-1I,HLS_INPUT_CLOCK=40.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=15.106300,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=17,HLS_SYN_LUT=350,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top (
        ap_clk,
        ap_rst,
        hand_x,
        hand_y,
        detected,
        vga_x,
        vga_y,
        vsync,
        rst_n,
        R_out,
        G_out,
        B_out
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input  [9:0] hand_x;
input  [9:0] hand_y;
input  [0:0] detected;
input  [9:0] vga_x;
input  [9:0] vga_y;
input  [0:0] vsync;
input  [0:0] rst_n;
output  [9:0] R_out;
output  [9:0] G_out;
output  [9:0] B_out;

reg   [4:0] box_col;
reg   [3:0] box_row;
reg   [1:0] direction;
reg   [3:0] frame_count;
reg   [0:0] vsync_prev;
wire   [4:0] select_ln116_fu_422_p3;
reg   [4:0] ap_phi_mux_storemerge4_phi_fu_176_p4;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] rst_n_read_read_fu_110_p2;
wire   [0:0] vsync_fall_fu_278_p2;
wire   [0:0] icmp_ln96_fu_372_p2;
wire   [1:0] direction_load_load_fu_396_p1;
wire   [4:0] select_ln123_fu_497_p3;
reg   [4:0] ap_phi_mux_box_col_loc_3_phi_fu_185_p10;
wire   [3:0] select_ln102_fu_470_p3;
reg   [3:0] ap_phi_mux_box_row_loc_3_phi_fu_201_p10;
wire   [3:0] select_ln109_fu_443_p3;
wire   [0:0] box_on_fu_544_p2;
reg   [0:0] ap_phi_mux_storemerge12_phi_fu_216_p4;
wire   [1:0] storemerge283_0_0_s_fu_342_p9;
wire   [0:0] detected_read_read_fu_134_p2;
reg   [1:0] ap_sig_allocacmp_direction_load;
wire   [3:0] add_ln131_fu_378_p2;
wire   [9:0] storemerge12_cast_fu_551_p3;
wire   [0:0] xor_ln65_fu_272_p2;
wire   [0:0] top_half_fu_290_p2;
wire   [0:0] icmp_ln77_fu_296_p2;
wire   [0:0] or_ln85_fu_308_p2;
wire   [0:0] xor_ln77_1_fu_322_p2;
wire   [0:0] xor_ln77_fu_302_p2;
wire   [0:0] and_ln77_fu_328_p2;
wire   [1:0] storemerge283_0_0_s_fu_342_p2;
wire   [1:0] storemerge283_0_0_s_fu_342_p7;
wire   [1:0] storemerge283_0_0_s_fu_342_p8;
wire   [0:0] icmp_ln116_fu_410_p2;
wire   [4:0] add_ln119_fu_416_p2;
wire   [0:0] icmp_ln109_fu_431_p2;
wire   [3:0] add_ln112_fu_437_p2;
wire   [0:0] icmp_ln102_fu_458_p2;
wire   [3:0] add_ln105_fu_464_p2;
wire   [0:0] icmp_ln123_fu_485_p2;
wire   [4:0] add_ln126_fu_491_p2;
wire   [4:0] cell_col_fu_512_p4;
wire   [3:0] cell_row_fu_522_p4;
wire   [0:0] icmp_ln139_fu_532_p2;
wire   [0:0] icmp_ln139_1_fu_538_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_condition_99;
reg    ap_condition_76;
reg    ap_condition_65;
reg    ap_condition_61;
reg    ap_condition_96;
wire  signed [1:0] storemerge283_0_0_s_fu_342_p1;
wire   [1:0] storemerge283_0_0_s_fu_342_p3;
wire   [1:0] storemerge283_0_0_s_fu_342_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 box_col = 5'd10;
#0 box_row = 4'd7;
#0 direction = 2'd1;
#0 frame_count = 4'd0;
#0 vsync_prev = 1'd0;
#0 ap_CS_fsm = 1'd1;
end

(* dissolve_hierarchy = "yes" *) snake_top_sparsemux_7_2_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 2 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 2 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 2 ),
    .def_WIDTH( 2 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
sparsemux_7_2_2_1_1_U1(
    .din0(storemerge283_0_0_s_fu_342_p2),
    .din1(2'd0),
    .din2(2'd1),
    .def(storemerge283_0_0_s_fu_342_p7),
    .sel(storemerge283_0_0_s_fu_342_p8),
    .dout(storemerge283_0_0_s_fu_342_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_76)) begin
            box_col <= ap_phi_mux_storemerge4_phi_fu_176_p4;
        end else if ((rst_n_read_read_fu_110_p2 == 1'd0)) begin
            box_col <= 5'd10;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_61)) begin
            box_row <= select_ln102_fu_470_p3;
        end else if ((1'b1 == ap_condition_65)) begin
            box_row <= select_ln109_fu_443_p3;
        end else if ((rst_n_read_read_fu_110_p2 == 1'd0)) begin
            box_row <= 4'd7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((1'b1 == ap_condition_96)) begin
            direction <= storemerge283_0_0_s_fu_342_p9;
        end else if ((rst_n_read_read_fu_110_p2 == 1'd0)) begin
            direction <= 2'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln96_fu_372_p2 == 1'd0) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        frame_count <= add_ln131_fu_378_p2;
    end else if ((((rst_n_read_read_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        frame_count <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((rst_n_read_read_fu_110_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        vsync_prev <= vsync;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (((direction_load_load_fu_396_p1 == 2'd1) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1)) | ((direction_load_load_fu_396_p1 == 2'd2) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1))))) begin
        ap_phi_mux_box_col_loc_3_phi_fu_185_p10 = ap_phi_mux_storemerge4_phi_fu_176_p4;
    end else if ((((icmp_ln96_fu_372_p2 == 1'd0) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((vsync_fall_fu_278_p2 == 1'd0) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((direction_load_load_fu_396_p1 == 2'd3) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((direction_load_load_fu_396_p1 == 2'd0) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_phi_mux_box_col_loc_3_phi_fu_185_p10 = box_col;
    end else begin
        ap_phi_mux_box_col_loc_3_phi_fu_185_p10 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln96_fu_372_p2 == 1'd0) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((vsync_fall_fu_278_p2 == 1'd0) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state1) & (((direction_load_load_fu_396_p1 == 2'd1) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1)) | ((direction_load_load_fu_396_p1 == 2'd2) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1)))))) begin
        ap_phi_mux_box_row_loc_3_phi_fu_201_p10 = box_row;
    end else if (((direction_load_load_fu_396_p1 == 2'd3) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_box_row_loc_3_phi_fu_201_p10 = select_ln109_fu_443_p3;
    end else if (((direction_load_load_fu_396_p1 == 2'd0) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_box_row_loc_3_phi_fu_201_p10 = select_ln102_fu_470_p3;
    end else begin
        ap_phi_mux_box_row_loc_3_phi_fu_201_p10 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((rst_n_read_read_fu_110_p2 == 1'd0)) begin
            ap_phi_mux_storemerge12_phi_fu_216_p4 = 1'd0;
        end else if ((rst_n_read_read_fu_110_p2 == 1'd1)) begin
            ap_phi_mux_storemerge12_phi_fu_216_p4 = box_on_fu_544_p2;
        end else begin
            ap_phi_mux_storemerge12_phi_fu_216_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge12_phi_fu_216_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_99)) begin
        if ((direction_load_load_fu_396_p1 == 2'd1)) begin
            ap_phi_mux_storemerge4_phi_fu_176_p4 = select_ln123_fu_497_p3;
        end else if ((direction_load_load_fu_396_p1 == 2'd2)) begin
            ap_phi_mux_storemerge4_phi_fu_176_p4 = select_ln116_fu_422_p3;
        end else begin
            ap_phi_mux_storemerge4_phi_fu_176_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge4_phi_fu_176_p4 = 'bx;
    end
end

always @ (*) begin
    if (((detected_read_read_fu_134_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_direction_load = storemerge283_0_0_s_fu_342_p9;
    end else begin
        ap_sig_allocacmp_direction_load = direction;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_out = storemerge12_cast_fu_551_p3;

assign G_out = storemerge12_cast_fu_551_p3;

assign R_out = storemerge12_cast_fu_551_p3;

assign add_ln105_fu_464_p2 = ($signed(box_row) + $signed(4'd15));

assign add_ln112_fu_437_p2 = (box_row + 4'd1);

assign add_ln119_fu_416_p2 = ($signed(box_col) + $signed(5'd31));

assign add_ln126_fu_491_p2 = (box_col + 5'd1);

assign add_ln131_fu_378_p2 = (frame_count + 4'd1);

assign and_ln77_fu_328_p2 = (xor_ln77_1_fu_322_p2 & top_half_fu_290_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_condition_61 = ((direction_load_load_fu_396_p1 == 2'd0) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_65 = ((direction_load_load_fu_396_p1 == 2'd3) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_76 = (((direction_load_load_fu_396_p1 == 2'd1) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1)) | ((direction_load_load_fu_396_p1 == 2'd2) & (icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_96 = ((detected_read_read_fu_134_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_99 = ((icmp_ln96_fu_372_p2 == 1'd1) & (vsync_fall_fu_278_p2 == 1'd1) & (rst_n_read_read_fu_110_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1));
end

assign box_on_fu_544_p2 = (icmp_ln139_fu_532_p2 & icmp_ln139_1_fu_538_p2);

assign cell_col_fu_512_p4 = {{vga_x[9:5]}};

assign cell_row_fu_522_p4 = {{vga_y[8:5]}};

assign detected_read_read_fu_134_p2 = detected;

assign direction_load_load_fu_396_p1 = ap_sig_allocacmp_direction_load;

assign icmp_ln102_fu_458_p2 = ((box_row == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_431_p2 = ((box_row == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln116_fu_410_p2 = ((box_col == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_485_p2 = ((box_col == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln139_1_fu_538_p2 = ((cell_row_fu_522_p4 == ap_phi_mux_box_row_loc_3_phi_fu_201_p10) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_532_p2 = ((cell_col_fu_512_p4 == ap_phi_mux_box_col_loc_3_phi_fu_185_p10) ? 1'b1 : 1'b0);

assign icmp_ln77_fu_296_p2 = ((hand_x > 10'd319) ? 1'b1 : 1'b0);

assign icmp_ln96_fu_372_p2 = ((frame_count == 4'd14) ? 1'b1 : 1'b0);

assign or_ln85_fu_308_p2 = (top_half_fu_290_p2 | icmp_ln77_fu_296_p2);

assign rst_n_read_read_fu_110_p2 = rst_n;

assign select_ln102_fu_470_p3 = ((icmp_ln102_fu_458_p2[0:0] == 1'b1) ? 4'd14 : add_ln105_fu_464_p2);

assign select_ln109_fu_443_p3 = ((icmp_ln109_fu_431_p2[0:0] == 1'b1) ? 4'd0 : add_ln112_fu_437_p2);

assign select_ln116_fu_422_p3 = ((icmp_ln116_fu_410_p2[0:0] == 1'b1) ? 5'd19 : add_ln119_fu_416_p2);

assign select_ln123_fu_497_p3 = ((icmp_ln123_fu_485_p2[0:0] == 1'b1) ? 5'd0 : add_ln126_fu_491_p2);

assign storemerge12_cast_fu_551_p3 = ((ap_phi_mux_storemerge12_phi_fu_216_p4[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign storemerge283_0_0_s_fu_342_p2 = ((or_ln85_fu_308_p2[0:0] == 1'b1) ? 2'd3 : 2'd2);

assign storemerge283_0_0_s_fu_342_p7 = 'bx;

assign storemerge283_0_0_s_fu_342_p8 = {{xor_ln77_fu_302_p2}, {and_ln77_fu_328_p2}};

assign top_half_fu_290_p2 = ((hand_y < 10'd240) ? 1'b1 : 1'b0);

assign vsync_fall_fu_278_p2 = (xor_ln65_fu_272_p2 & vsync_prev);

assign xor_ln65_fu_272_p2 = (vsync ^ 1'd1);

assign xor_ln77_1_fu_322_p2 = (icmp_ln77_fu_296_p2 ^ 1'd1);

assign xor_ln77_fu_302_p2 = (top_half_fu_290_p2 ^ 1'd1);

endmodule //snake_top
