// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top_snake_top_Pipeline_VITIS_LOOP_218_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        snake_len_load,
        snake_col_address0,
        snake_col_ce0,
        snake_col_we0,
        snake_col_d0,
        snake_col_address1,
        snake_col_ce1,
        snake_col_q1,
        snake_row_address0,
        snake_row_ce0,
        snake_row_we0,
        snake_row_d0,
        snake_row_address1,
        snake_row_ce1,
        snake_row_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] snake_len_load;
output  [2:0] snake_col_address0;
output   snake_col_ce0;
output   snake_col_we0;
output  [4:0] snake_col_d0;
output  [2:0] snake_col_address1;
output   snake_col_ce1;
input  [4:0] snake_col_q1;
output  [2:0] snake_row_address0;
output   snake_row_ce0;
output   snake_row_we0;
output  [3:0] snake_row_d0;
output  [2:0] snake_row_address1;
output   snake_row_ce1;
input  [3:0] snake_row_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln218_fu_104_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [2:0] i_reg_145;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln220_fu_110_p2;
reg   [0:0] icmp_ln220_reg_153;
wire   [63:0] zext_ln220_fu_122_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln218_fu_133_p1;
reg   [2:0] i_1_fu_34;
wire   [2:0] i_4_fu_116_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i;
reg    snake_col_ce1_local;
reg    snake_col_we0_local;
reg    snake_col_ce0_local;
reg    snake_row_ce1_local;
reg    snake_row_we0_local;
reg    snake_row_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_1_fu_34 = 3'd0;
#0 ap_done_reg = 1'b0;
end

snake_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln218_fu_104_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_34 <= i_4_fu_116_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_34 <= 3'd4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_145 <= ap_sig_allocacmp_i;
        icmp_ln220_reg_153 <= icmp_ln220_fu_110_p2;
    end
end

always @ (*) begin
    if (((icmp_ln218_fu_104_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 3'd4;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_34;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snake_col_ce0_local = 1'b1;
    end else begin
        snake_col_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snake_col_ce1_local = 1'b1;
    end else begin
        snake_col_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln220_reg_153 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snake_col_we0_local = 1'b1;
    end else begin
        snake_col_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snake_row_ce0_local = 1'b1;
    end else begin
        snake_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snake_row_ce1_local = 1'b1;
    end else begin
        snake_row_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln220_reg_153 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        snake_row_we0_local = 1'b1;
    end else begin
        snake_row_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_4_fu_116_p2 = ($signed(ap_sig_allocacmp_i) + $signed(3'd7));

assign icmp_ln218_fu_104_p2 = ((ap_sig_allocacmp_i == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln220_fu_110_p2 = ((ap_sig_allocacmp_i < snake_len_load) ? 1'b1 : 1'b0);

assign snake_col_address0 = zext_ln218_fu_133_p1;

assign snake_col_address1 = zext_ln220_fu_122_p1;

assign snake_col_ce0 = snake_col_ce0_local;

assign snake_col_ce1 = snake_col_ce1_local;

assign snake_col_d0 = snake_col_q1;

assign snake_col_we0 = snake_col_we0_local;

assign snake_row_address0 = zext_ln218_fu_133_p1;

assign snake_row_address1 = zext_ln220_fu_122_p1;

assign snake_row_ce0 = snake_row_ce0_local;

assign snake_row_ce1 = snake_row_ce1_local;

assign snake_row_d0 = snake_row_q1;

assign snake_row_we0 = snake_row_we0_local;

assign zext_ln218_fu_133_p1 = i_reg_145;

assign zext_ln220_fu_122_p1 = i_4_fu_116_p2;

endmodule //snake_top_snake_top_Pipeline_VITIS_LOOP_218_2
