// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="snake_top_snake_top,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7z010-clg225-1I,HLS_INPUT_CLOCK=40.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.428300,HLS_SYN_LAT=12,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=431,HLS_SYN_LUT=1681,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top (
        ap_clk,
        ap_rst,
        coord_x,
        coord_y,
        detected,
        vga_x,
        vga_y,
        vsync,
        rst_n,
        R_out,
        G_out,
        B_out
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;

input   ap_clk;
input   ap_rst;
input  [9:0] coord_x;
input  [9:0] coord_y;
input  [0:0] detected;
input  [9:0] vga_x;
input  [9:0] vga_y;
input  [0:0] vsync;
input  [0:0] rst_n;
output  [9:0] R_out;
output  [9:0] G_out;
output  [9:0] B_out;

reg   [2:0] snake_len;
reg   [4:0] food_col;
reg   [3:0] food_row;
reg   [0:0] game_state;
reg   [6:0] start_hold_count;
reg   [2:0] snake_col_address0;
reg    snake_col_ce0;
reg    snake_col_we0;
reg   [4:0] snake_col_d0;
wire   [4:0] snake_col_q0;
reg    snake_col_ce1;
wire   [4:0] snake_col_q1;
reg   [2:0] snake_row_address0;
reg    snake_row_ce0;
reg    snake_row_we0;
reg   [3:0] snake_row_d0;
wire   [3:0] snake_row_q0;
reg    snake_row_ce1;
wire   [3:0] snake_row_q1;
reg   [1:0] direction;
reg   [3:0] frame_count;
reg   [0:0] vsync_prev;
reg   [7:0] rand_state;
reg   [4:0] reg_541;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state18;
wire   [0:0] rst_n_read_read_fu_188_p2;
reg   [0:0] rst_n_read_reg_1451;
wire    ap_CS_fsm_state1;
reg   [9:0] vga_y_read_reg_1455;
reg   [9:0] vga_x_read_reg_1461;
wire   [0:0] detected_read_read_fu_212_p2;
reg   [0:0] detected_read_reg_1467;
reg   [9:0] coord_y_read_reg_1472;
reg   [9:0] coord_x_read_reg_1477;
reg   [2:0] snake_len_load_reg_1488;
reg   [4:0] food_col_load_reg_1503;
reg   [3:0] food_row_load_reg_1513;
wire   [0:0] game_state_load_load_fu_560_p1;
reg   [0:0] game_state_load_reg_1523;
wire   [0:0] vsync_fall_fu_584_p2;
reg   [0:0] vsync_fall_reg_1528;
wire   [7:0] add_ln103_fu_612_p2;
reg   [7:0] add_ln103_reg_1532;
wire   [0:0] start_hold_count_flag_0_fu_746_p2;
wire   [6:0] empty_fu_752_p3;
wire   [0:0] icmp_ln179_fu_830_p2;
reg   [0:0] icmp_ln179_reg_1554;
reg   [3:0] snake_row_load_reg_1558;
wire   [3:0] select_ln197_fu_943_p3;
wire   [3:0] select_ln190_fu_964_p3;
wire   [0:0] icmp_ln228_fu_1003_p2;
reg   [0:0] icmp_ln228_reg_1577;
wire    ap_CS_fsm_state6;
wire   [0:0] and_ln235_fu_1019_p2;
reg   [0:0] and_ln235_reg_1581;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln237_fu_1025_p2;
reg   [0:0] icmp_ln237_reg_1585;
wire   [2:0] add_ln241_fu_1035_p2;
wire    ap_CS_fsm_state8;
wire   [3:0] grp_fu_1060_p2;
reg   [3:0] urem_ln245_reg_1599;
wire    ap_CS_fsm_state16;
wire   [3:0] next_food_row_fu_1066_p1;
reg   [3:0] next_food_row_reg_1604;
wire   [0:0] icmp_ln247_1_fu_1069_p2;
reg   [0:0] icmp_ln247_1_reg_1609;
wire   [4:0] storemerge_fu_1116_p3;
wire    ap_CS_fsm_state19;
reg   [4:0] cell_col_reg_1619;
reg   [3:0] cell_row_reg_1625;
wire   [0:0] icmp_ln297_fu_1226_p2;
reg   [0:0] icmp_ln297_reg_1631;
wire   [0:0] icmp_ln297_1_fu_1232_p2;
reg   [0:0] icmp_ln297_1_reg_1636;
wire   [0:0] icmp_ln309_fu_1302_p2;
reg   [0:0] icmp_ln309_reg_1641;
wire   [0:0] icmp_ln310_fu_1308_p2;
reg   [0:0] icmp_ln310_reg_1646;
wire   [0:0] food_on_fu_1324_p2;
reg   [0:0] food_on_reg_1651;
wire    ap_CS_fsm_state20;
wire   [0:0] and_ln308_1_fu_1341_p2;
reg   [0:0] and_ln308_1_reg_1657;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_ready;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_we0;
wire   [4:0] grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_d0;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_we0;
wire   [3:0] grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_d0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_ready;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_we0;
wire   [4:0] grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_d0;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_address1;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_ce1;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_ce0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_we0;
wire   [3:0] grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_d0;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_address1;
wire    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_ce1;
wire    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start;
wire    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_done;
wire    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_idle;
wire    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_ready;
wire   [0:0] grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_on_out;
wire    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_on_out_ap_vld;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_col_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_col_ce0;
wire   [2:0] grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_row_address0;
wire    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_row_ce0;
wire   [4:0] select_ln204_fu_922_p3;
reg   [4:0] ap_phi_mux_storemerge17_phi_fu_286_p4;
wire   [1:0] direction_load_load_fu_896_p1;
wire   [4:0] select_ln211_fu_985_p3;
reg   [3:0] empty_15_reg_294;
reg   [4:0] empty_16_reg_306;
reg   [2:0] snake_len_loc_0_reg_319;
reg   [2:0] snake_len_loc_4_reg_328;
wire   [0:0] icmp_ln134_fu_760_p2;
reg   [4:0] food_col_loc_3_reg_347;
reg   [3:0] food_row_loc_3_reg_364;
reg   [0:0] game_state_loc_2_reg_381;
reg   [0:0] start_hold_count_flag_3_reg_405;
reg   [6:0] start_hold_count_new_3_reg_429;
reg   [0:0] ap_phi_mux_start_hold_count_flag_4_phi_fu_457_p4;
reg   [0:0] start_hold_count_flag_4_reg_453;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state3;
reg   [6:0] ap_phi_mux_start_hold_count_new_4_phi_fu_469_p4;
reg   [6:0] start_hold_count_new_4_reg_465;
wire   [0:0] select_ln312_1_fu_1403_p3;
reg   [0:0] ap_phi_mux_storemerge2_phi_fu_481_p4;
reg   [0:0] storemerge2_reg_477;
wire   [9:0] select_ln312_2_fu_1411_p3;
reg   [9:0] ap_phi_mux_storemerge1_phi_fu_492_p4;
reg   [9:0] storemerge1_reg_488;
wire   [0:0] and_ln312_fu_1420_p2;
reg   [0:0] ap_phi_mux_storemerge3_phi_fu_504_p4;
reg   [0:0] storemerge3_reg_500;
reg    grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    snake_col_we0_out;
wire    snake_row_we0_out;
reg    grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start_reg;
wire   [63:0] zext_ln239_fu_1030_p1;
wire   [1:0] select_ln162_fu_812_p3;
wire   [0:0] in_dead_zone_fu_778_p2;
wire   [3:0] add_ln265_fu_836_p2;
reg    snake_col_we0_local;
reg   [4:0] snake_col_d0_local;
reg    snake_col_ce0_local;
reg   [2:0] snake_col_address0_local;
wire    ap_CS_fsm_state17;
reg    snake_row_we0_local;
reg   [3:0] snake_row_d0_local;
reg    snake_row_ce0_local;
reg   [2:0] snake_row_address0_local;
wire   [0:0] xor_ln97_fu_578_p2;
wire   [7:0] shl_ln103_fu_600_p2;
wire   [7:0] add_ln103_1_fu_606_p2;
wire   [10:0] zext_ln106_fu_624_p1;
wire   [10:0] start_dx_fu_628_p2;
wire   [10:0] zext_ln107_fu_638_p1;
wire   [10:0] start_dy_fu_642_p2;
wire   [9:0] trunc_ln106_fu_634_p1;
wire   [0:0] tmp_fu_652_p3;
wire   [9:0] sub_ln109_fu_660_p2;
wire   [9:0] trunc_ln107_fu_648_p1;
wire   [0:0] tmp_1_fu_674_p3;
wire   [9:0] sub_ln110_fu_682_p2;
wire   [9:0] abs_start_dx_fu_666_p3;
wire   [0:0] icmp_ln118_fu_696_p2;
wire   [9:0] abs_start_dy_fu_688_p3;
wire   [0:0] and_ln117_fu_702_p2;
wire   [0:0] icmp_ln119_fu_708_p2;
wire   [0:0] icmp_ln126_fu_720_p2;
wire   [6:0] add_ln127_fu_726_p2;
wire   [0:0] in_start_box_fu_714_p2;
wire   [0:0] not_in_start_box_fu_740_p2;
wire   [6:0] select_ln126_fu_732_p3;
wire   [0:0] xor_ln164_fu_790_p2;
wire   [0:0] icmp_ln162_fu_784_p2;
wire   [1:0] select_ln171_1_fu_796_p3;
wire   [1:0] select_ln171_fu_804_p3;
wire   [0:0] icmp_ln204_fu_910_p2;
wire   [4:0] add_ln207_fu_916_p2;
wire   [0:0] icmp_ln197_fu_931_p2;
wire   [3:0] add_ln200_fu_937_p2;
wire   [0:0] icmp_ln190_fu_952_p2;
wire   [3:0] add_ln193_fu_958_p2;
wire   [0:0] icmp_ln211_fu_973_p2;
wire   [4:0] add_ln214_fu_979_p2;
wire   [1:0] tmp_2_fu_994_p4;
wire   [0:0] icmp_ln235_fu_1009_p2;
wire   [0:0] icmp_ln235_1_fu_1014_p2;
wire   [5:0] grp_fu_1046_p1;
wire   [4:0] grp_fu_1060_p0;
wire   [4:0] grp_fu_1046_p2;
wire   [4:0] next_food_col_fu_1081_p1;
wire   [0:0] icmp_ln247_fu_1085_p2;
wire   [0:0] icmp_ln249_fu_1096_p2;
wire   [4:0] add_ln252_fu_1102_p2;
wire   [0:0] and_ln247_fu_1091_p2;
wire   [4:0] select_ln249_fu_1108_p3;
wire   [10:0] zext_ln302_fu_1150_p1;
wire   [10:0] zext_ln290_1_fu_1156_p1;
wire   [10:0] hand_dx_fu_1159_p2;
wire   [10:0] zext_ln290_fu_1153_p1;
wire   [10:0] zext_ln291_fu_1169_p1;
wire   [10:0] hand_dy_fu_1172_p2;
wire   [9:0] trunc_ln290_fu_1165_p1;
wire   [0:0] tmp_3_fu_1182_p3;
wire   [9:0] sub_ln293_fu_1190_p2;
wire   [9:0] trunc_ln291_fu_1178_p1;
wire   [0:0] tmp_4_fu_1204_p3;
wire   [9:0] sub_ln294_fu_1212_p2;
wire   [9:0] abs_hand_dx_fu_1196_p3;
wire   [9:0] abs_hand_dy_fu_1218_p3;
wire   [10:0] box_dx_fu_1238_p2;
wire   [10:0] box_dy_fu_1248_p2;
wire   [9:0] trunc_ln301_fu_1244_p1;
wire   [0:0] tmp_5_fu_1258_p3;
wire   [9:0] sub_ln304_fu_1266_p2;
wire   [9:0] trunc_ln302_fu_1254_p1;
wire   [0:0] tmp_6_fu_1280_p3;
wire   [9:0] sub_ln305_fu_1288_p2;
wire   [9:0] abs_box_dx_fu_1272_p3;
wire   [9:0] abs_box_dy_fu_1294_p3;
wire   [0:0] icmp_ln284_fu_1314_p2;
wire   [0:0] icmp_ln284_1_fu_1319_p2;
wire   [0:0] xor_ln308_fu_1330_p2;
wire   [0:0] and_ln308_fu_1336_p2;
wire   [0:0] hand_on_fu_1349_p2;
wire   [0:0] or_ln312_fu_1358_p2;
wire   [0:0] hand_on_1_fu_1353_p2;
wire   [9:0] select_ln312_3_fu_1363_p3;
wire   [0:0] xor_ln312_fu_1385_p2;
wire   [0:0] or_ln312_1_fu_1371_p2;
wire   [9:0] select_ln312_fu_1377_p3;
wire   [9:0] select_ln308_fu_1396_p3;
wire   [0:0] or_ln312_2_fu_1390_p2;
reg    grp_fu_1046_ap_start;
wire    grp_fu_1046_ap_done;
reg    grp_fu_1060_ap_start;
wire    grp_fu_1060_ap_done;
reg   [20:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_condition_862;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 snake_len = 3'd1;
#0 food_col = 5'd5;
#0 food_row = 4'd5;
#0 game_state = 1'd0;
#0 start_hold_count = 7'd0;
#0 direction = 2'd1;
#0 frame_count = 4'd0;
#0 vsync_prev = 1'd0;
#0 rand_state = 8'd90;
#0 ap_CS_fsm = 21'd1;
#0 grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start_reg = 1'b0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start_reg = 1'b0;
#0 grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start_reg = 1'b0;
end

snake_top_snake_col_RAM_AUTO_1R1W #(
    .DataWidth( 5 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
snake_col_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(snake_col_address0),
    .ce0(snake_col_ce0),
    .we0(snake_col_we0),
    .d0(snake_col_d0),
    .q0(snake_col_q0),
    .address1(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_address1),
    .ce1(snake_col_ce1),
    .q1(snake_col_q1)
);

snake_top_snake_row_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
snake_row_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(snake_row_address0),
    .ce0(snake_row_ce0),
    .we0(snake_row_we0),
    .d0(snake_row_d0),
    .q0(snake_row_q0),
    .address1(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_address1),
    .ce1(snake_row_ce1),
    .q1(snake_row_q1)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_71_1 grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_ready),
    .snake_col_address0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_address0),
    .snake_col_ce0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_ce0),
    .snake_col_we0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_we0),
    .snake_col_d0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_d0),
    .snake_row_address0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_address0),
    .snake_row_ce0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_ce0),
    .snake_row_we0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_we0),
    .snake_row_d0(grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_d0)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_218_2 grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_ready),
    .snake_len_load(snake_len_load_reg_1488),
    .snake_col_address0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_address0),
    .snake_col_ce0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_ce0),
    .snake_col_we0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_we0),
    .snake_col_d0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_d0),
    .snake_col_address1(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_address1),
    .snake_col_ce1(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_ce1),
    .snake_col_q1(snake_col_q1),
    .snake_row_address0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_address0),
    .snake_row_ce0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_ce0),
    .snake_row_we0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_we0),
    .snake_row_d0(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_d0),
    .snake_row_address1(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_address1),
    .snake_row_ce1(grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_ce1),
    .snake_row_q1(snake_row_q1)
);

snake_top_snake_top_Pipeline_VITIS_LOOP_274_3 grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start),
    .ap_done(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_done),
    .ap_idle(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_idle),
    .ap_ready(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_ready),
    .snake_len_loc_4(snake_len_loc_4_reg_328),
    .cell_col(cell_col_reg_1619),
    .cell_row(cell_row_reg_1625),
    .snake_on_out(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_on_out),
    .snake_on_out_ap_vld(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_on_out_ap_vld),
    .snake_col_address0(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_col_address0),
    .snake_col_ce0(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_col_ce0),
    .snake_col_q0(snake_col_q0),
    .snake_row_address0(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_row_address0),
    .snake_row_ce0(grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_row_ce0),
    .snake_row_q0(snake_row_q0)
);

snake_top_urem_8ns_6ns_5_12_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 5 ))
urem_8ns_6ns_5_12_seq_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1046_ap_start),
    .done(grp_fu_1046_ap_done),
    .din0(add_ln103_reg_1532),
    .din1(grp_fu_1046_p1),
    .ce(1'b1),
    .dout(grp_fu_1046_p2)
);

snake_top_urem_5ns_5ns_4_9_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_5ns_5ns_4_9_seq_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1060_ap_start),
    .done(grp_fu_1060_ap_done),
    .din0(grp_fu_1060_p0),
    .din1(5'd15),
    .ce(1'b1),
    .dout(grp_fu_1060_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start_reg <= 1'b1;
        end else if ((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_ready == 1'b1)) begin
            grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_188_p2 == 1'd1) & (in_dead_zone_fu_778_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1) & (detected_read_read_fu_212_p2 == 1'd1))) begin
        direction <= select_ln162_fu_812_p3;
    end else if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        direction <= 2'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((direction_load_load_fu_896_p1 == 2'd1) | (direction_load_load_fu_896_p1 == 2'd2))) begin
            empty_15_reg_294 <= snake_row_q0;
        end else if ((direction_load_load_fu_896_p1 == 2'd3)) begin
            empty_15_reg_294 <= select_ln197_fu_943_p3;
        end else if ((direction_load_load_fu_896_p1 == 2'd0)) begin
            empty_15_reg_294 <= select_ln190_fu_964_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((direction_load_load_fu_896_p1 == 2'd1) | (direction_load_load_fu_896_p1 == 2'd2)))) begin
        empty_16_reg_306 <= ap_phi_mux_storemerge17_phi_fu_286_p4;
    end else if ((((direction_load_load_fu_896_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state4)) | ((direction_load_load_fu_896_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        empty_16_reg_306 <= snake_col_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        food_col <= 5'd5;
    end else if (((1'd1 == and_ln235_reg_1581) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln179_reg_1554 == 1'd1) & (vsync_fall_reg_1528 == 1'd1) & (game_state_load_reg_1523 == 1'd1))) begin
        food_col <= storemerge_fu_1116_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln235_fu_1019_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        food_col_loc_3_reg_347 <= food_col_load_reg_1503;
    end else if (((1'd1 == and_ln235_reg_1581) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln179_reg_1554 == 1'd1) & (vsync_fall_reg_1528 == 1'd1) & (game_state_load_reg_1523 == 1'd1))) begin
        food_col_loc_3_reg_347 <= storemerge_fu_1116_p3;
    end else if ((((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd0) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd0)))) begin
        food_col_loc_3_reg_347 <= food_col;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        food_row <= 4'd5;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        food_row <= next_food_row_fu_1066_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln235_fu_1019_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        food_row_loc_3_reg_364 <= food_row_load_reg_1513;
    end else if (((1'd1 == and_ln235_reg_1581) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln179_reg_1554 == 1'd1) & (vsync_fall_reg_1528 == 1'd1) & (game_state_load_reg_1523 == 1'd1))) begin
        food_row_loc_3_reg_364 <= next_food_row_reg_1604;
    end else if ((((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd0) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd0)))) begin
        food_row_loc_3_reg_364 <= food_row;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd0) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1))) begin
        frame_count <= add_ln265_fu_836_p2;
    end else if (((1'b1 == ap_CS_fsm_state4) | ((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)))) begin
        frame_count <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0))) begin
        game_state <= 1'd1;
    end else if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        game_state <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0))) begin
        game_state_loc_2_reg_381 <= 1'd0;
    end else if ((((1'd0 == and_ln235_fu_1019_p2) & (1'b1 == ap_CS_fsm_state7)) | ((1'd1 == and_ln235_reg_1581) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln179_reg_1554 == 1'd1) & (vsync_fall_reg_1528 == 1'd1) & (game_state_load_reg_1523 == 1'd1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd0) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)))) begin
        game_state_loc_2_reg_381 <= 1'd1;
    end else if (((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd0))) begin
        game_state_loc_2_reg_381 <= game_state;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1))) begin
        rand_state <= add_ln103_fu_612_p2;
    end else if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        rand_state <= 8'd90;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        snake_len <= 3'd1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln237_reg_1585 == 1'd1))) begin
        snake_len <= add_ln241_fu_1035_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln235_fu_1019_p2) & (1'b1 == ap_CS_fsm_state7) & (icmp_ln237_fu_1025_p2 == 1'd0))) begin
        snake_len_loc_0_reg_319 <= snake_len_load_reg_1488;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln237_reg_1585 == 1'd1))) begin
        snake_len_loc_0_reg_319 <= add_ln241_fu_1035_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln235_fu_1019_p2) & (1'b1 == ap_CS_fsm_state7))) begin
        snake_len_loc_4_reg_328 <= snake_len_load_reg_1488;
    end else if (((1'd1 == and_ln235_reg_1581) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln179_reg_1554 == 1'd1) & (vsync_fall_reg_1528 == 1'd1) & (game_state_load_reg_1523 == 1'd1))) begin
        snake_len_loc_4_reg_328 <= snake_len_loc_0_reg_319;
    end else if ((((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd0) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd0)))) begin
        snake_len_loc_4_reg_328 <= snake_len;
    end
end

always @ (posedge ap_clk) begin
    if (((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0))) begin
        start_hold_count_flag_3_reg_405 <= start_hold_count_flag_0_fu_746_p2;
    end else if (((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln134_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0))) begin
        start_hold_count_flag_3_reg_405 <= 1'd1;
    end else if ((((1'd0 == and_ln235_fu_1019_p2) & (1'b1 == ap_CS_fsm_state7)) | ((1'd1 == and_ln235_reg_1581) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln179_reg_1554 == 1'd1) & (vsync_fall_reg_1528 == 1'd1) & (game_state_load_reg_1523 == 1'd1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd0) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd0)))) begin
        start_hold_count_flag_3_reg_405 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        start_hold_count_flag_4_reg_453 <= 1'd1;
    end else if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        start_hold_count_flag_4_reg_453 <= start_hold_count_flag_3_reg_405;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_862)) begin
        if ((icmp_ln134_fu_760_p2 == 1'd0)) begin
            start_hold_count_new_3_reg_429 <= empty_fu_752_p3;
        end else if ((icmp_ln134_fu_760_p2 == 1'd1)) begin
            start_hold_count_new_3_reg_429 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        start_hold_count_new_4_reg_465 <= 7'd0;
    end else if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        start_hold_count_new_4_reg_465 <= start_hold_count_new_3_reg_429;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        storemerge1_reg_488 <= 10'd0;
    end else if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        storemerge1_reg_488 <= select_ln312_2_fu_1411_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        storemerge2_reg_477 <= 1'd0;
    end else if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        storemerge2_reg_477 <= select_ln312_1_fu_1403_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        storemerge3_reg_500 <= 1'd0;
    end else if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        storemerge3_reg_500 <= and_ln312_fu_1420_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln103_reg_1532 <= add_ln103_fu_612_p2;
        coord_x_read_reg_1477 <= coord_x;
        coord_y_read_reg_1472 <= coord_y;
        detected_read_reg_1467 <= detected;
        food_col_load_reg_1503 <= food_col;
        food_row_load_reg_1513 <= food_row;
        game_state_load_reg_1523 <= game_state;
        icmp_ln179_reg_1554 <= icmp_ln179_fu_830_p2;
        rst_n_read_reg_1451 <= rst_n;
        snake_len_load_reg_1488 <= snake_len;
        vga_x_read_reg_1461 <= vga_x;
        vga_y_read_reg_1455 <= vga_y;
        vsync_fall_reg_1528 <= vsync_fall_fu_584_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        and_ln235_reg_1581 <= and_ln235_fu_1019_p2;
        icmp_ln237_reg_1585 <= icmp_ln237_fu_1025_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        and_ln308_1_reg_1657 <= and_ln308_1_fu_1341_p2;
        food_on_reg_1651 <= food_on_fu_1324_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        cell_col_reg_1619 <= {{vga_x_read_reg_1461[9:5]}};
        cell_row_reg_1625 <= {{vga_y_read_reg_1455[8:5]}};
        icmp_ln297_1_reg_1636 <= icmp_ln297_1_fu_1232_p2;
        icmp_ln297_reg_1631 <= icmp_ln297_fu_1226_p2;
        icmp_ln309_reg_1641 <= icmp_ln309_fu_1302_p2;
        icmp_ln310_reg_1646 <= icmp_ln310_fu_1308_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln228_reg_1577 <= icmp_ln228_fu_1003_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        icmp_ln247_1_reg_1609 <= icmp_ln247_1_fu_1069_p2;
        next_food_row_reg_1604 <= next_food_row_fu_1066_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_541 <= snake_col_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        snake_row_load_reg_1558 <= snake_row_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_start_hold_count_flag_4_phi_fu_457_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        start_hold_count <= ap_phi_mux_start_hold_count_new_4_phi_fu_469_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        urem_ln245_reg_1599 <= grp_fu_1060_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        vsync_prev <= vsync;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_phi_mux_start_hold_count_flag_4_phi_fu_457_p4 = start_hold_count_flag_3_reg_405;
    end else begin
        ap_phi_mux_start_hold_count_flag_4_phi_fu_457_p4 = start_hold_count_flag_4_reg_453;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_phi_mux_start_hold_count_new_4_phi_fu_469_p4 = start_hold_count_new_3_reg_429;
    end else begin
        ap_phi_mux_start_hold_count_new_4_phi_fu_469_p4 = start_hold_count_new_4_reg_465;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if ((direction_load_load_fu_896_p1 == 2'd1)) begin
            ap_phi_mux_storemerge17_phi_fu_286_p4 = select_ln211_fu_985_p3;
        end else if ((direction_load_load_fu_896_p1 == 2'd2)) begin
            ap_phi_mux_storemerge17_phi_fu_286_p4 = select_ln204_fu_922_p3;
        end else begin
            ap_phi_mux_storemerge17_phi_fu_286_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge17_phi_fu_286_p4 = 'bx;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_phi_mux_storemerge1_phi_fu_492_p4 = select_ln312_2_fu_1411_p3;
    end else begin
        ap_phi_mux_storemerge1_phi_fu_492_p4 = storemerge1_reg_488;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_phi_mux_storemerge2_phi_fu_481_p4 = select_ln312_1_fu_1403_p3;
    end else begin
        ap_phi_mux_storemerge2_phi_fu_481_p4 = storemerge2_reg_477;
    end
end

always @ (*) begin
    if (((rst_n_read_reg_1451 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_phi_mux_storemerge3_phi_fu_504_p4 = and_ln312_fu_1420_p2;
    end else begin
        ap_phi_mux_storemerge3_phi_fu_504_p4 = storemerge3_reg_500;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_1046_ap_start = 1'b1;
    end else begin
        grp_fu_1046_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_1060_ap_start = 1'b1;
    end else begin
        grp_fu_1060_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        snake_col_address0 = grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_col_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_col_address0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_col_address0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_address0;
    end else begin
        snake_col_address0 = snake_col_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        snake_col_address0_local = zext_ln239_fu_1030_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        snake_col_address0_local = 3'd1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state17) | ((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)))) begin
        snake_col_address0_local = 3'd0;
    end else begin
        snake_col_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        snake_col_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_col_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_col_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_col_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_ce0;
    end else begin
        snake_col_ce0 = snake_col_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)))) begin
        snake_col_ce0_local = 1'b1;
    end else begin
        snake_col_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_col_ce1 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_ce1;
    end else begin
        snake_col_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_col_d0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_col_d0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_d0;
    end else begin
        snake_col_d0 = snake_col_d0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        snake_col_d0_local = reg_541;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        snake_col_d0_local = ap_phi_mux_storemerge17_phi_fu_286_p4;
    end else if (((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        snake_col_d0_local = 5'd10;
    end else begin
        snake_col_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_col_we0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_col_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_col_we0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_col_we0;
    end else begin
        snake_col_we0 = (snake_col_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state4) & ((direction_load_load_fu_896_p1 == 2'd1) | (direction_load_load_fu_896_p1 == 2'd2))) | ((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln237_reg_1585 == 1'd1)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln228_reg_1577 == 1'd0)))) begin
        snake_col_we0_local = 1'b1;
    end else begin
        snake_col_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        snake_row_address0 = grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_row_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_row_address0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_row_address0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_address0;
    end else begin
        snake_row_address0 = snake_row_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        snake_row_address0_local = zext_ln239_fu_1030_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        snake_row_address0_local = 3'd1;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)) | ((direction_load_load_fu_896_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state4)) | ((direction_load_load_fu_896_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        snake_row_address0_local = 3'd0;
    end else begin
        snake_row_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        snake_row_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_row_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_row_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_row_ce0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_ce0;
    end else begin
        snake_row_ce0 = snake_row_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1)) | ((direction_load_load_fu_896_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state4)) | ((direction_load_load_fu_896_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        snake_row_ce0_local = 1'b1;
    end else begin
        snake_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_row_ce1 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_ce1;
    end else begin
        snake_row_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_row_d0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_row_d0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_d0;
    end else begin
        snake_row_d0 = snake_row_d0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        snake_row_d0_local = snake_row_load_reg_1558;
    end else if (((direction_load_load_fu_896_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        snake_row_d0_local = select_ln190_fu_964_p3;
    end else if (((direction_load_load_fu_896_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        snake_row_d0_local = select_ln197_fu_943_p3;
    end else if (((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        snake_row_d0_local = 4'd7;
    end else begin
        snake_row_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        snake_row_we0 = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_snake_row_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        snake_row_we0 = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_snake_row_we0;
    end else begin
        snake_row_we0 = (snake_row_we0_out | 1'b0);
    end
end

always @ (*) begin
    if ((((rst_n_read_read_fu_188_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((direction_load_load_fu_896_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state4)) | ((direction_load_load_fu_896_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state8) & (icmp_ln237_reg_1585 == 1'd1)) | ((1'b1 == ap_CS_fsm_state7) & (icmp_ln228_reg_1577 == 1'd0)))) begin
        snake_row_we0_local = 1'b1;
    end else begin
        snake_row_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (icmp_ln179_fu_830_p2 == 1'd1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((1'b1 == ap_CS_fsm_state1) & ((((rst_n_read_read_fu_188_p2 == 1'd1) & (icmp_ln179_fu_830_p2 == 1'd0)) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0))) | ((rst_n_read_read_fu_188_p2 == 1'd1) & (vsync_fall_fu_584_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'd1 == and_ln235_fu_1019_p2) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_out = ((ap_phi_mux_storemerge3_phi_fu_504_p4[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign G_out = ap_phi_mux_storemerge1_phi_fu_492_p4;

assign R_out = ((ap_phi_mux_storemerge2_phi_fu_481_p4[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign abs_box_dx_fu_1272_p3 = ((tmp_5_fu_1258_p3[0:0] == 1'b1) ? sub_ln304_fu_1266_p2 : trunc_ln301_fu_1244_p1);

assign abs_box_dy_fu_1294_p3 = ((tmp_6_fu_1280_p3[0:0] == 1'b1) ? sub_ln305_fu_1288_p2 : trunc_ln302_fu_1254_p1);

assign abs_hand_dx_fu_1196_p3 = ((tmp_3_fu_1182_p3[0:0] == 1'b1) ? sub_ln293_fu_1190_p2 : trunc_ln290_fu_1165_p1);

assign abs_hand_dy_fu_1218_p3 = ((tmp_4_fu_1204_p3[0:0] == 1'b1) ? sub_ln294_fu_1212_p2 : trunc_ln291_fu_1178_p1);

assign abs_start_dx_fu_666_p3 = ((tmp_fu_652_p3[0:0] == 1'b1) ? sub_ln109_fu_660_p2 : trunc_ln106_fu_634_p1);

assign abs_start_dy_fu_688_p3 = ((tmp_1_fu_674_p3[0:0] == 1'b1) ? sub_ln110_fu_682_p2 : trunc_ln107_fu_648_p1);

assign add_ln103_1_fu_606_p2 = (shl_ln103_fu_600_p2 + rand_state);

assign add_ln103_fu_612_p2 = (add_ln103_1_fu_606_p2 + 8'd29);

assign add_ln127_fu_726_p2 = (start_hold_count + 7'd1);

assign add_ln193_fu_958_p2 = ($signed(snake_row_q0) + $signed(4'd15));

assign add_ln200_fu_937_p2 = (snake_row_q0 + 4'd1);

assign add_ln207_fu_916_p2 = ($signed(snake_col_q0) + $signed(5'd31));

assign add_ln214_fu_979_p2 = (snake_col_q0 + 5'd1);

assign add_ln241_fu_1035_p2 = (snake_len_load_reg_1488 + 3'd1);

assign add_ln252_fu_1102_p2 = (next_food_col_fu_1081_p1 + 5'd1);

assign add_ln265_fu_836_p2 = (frame_count + 4'd1);

assign and_ln117_fu_702_p2 = (icmp_ln118_fu_696_p2 & detected);

assign and_ln235_fu_1019_p2 = (icmp_ln235_fu_1009_p2 & icmp_ln235_1_fu_1014_p2);

assign and_ln247_fu_1091_p2 = (icmp_ln247_fu_1085_p2 & icmp_ln247_1_reg_1609);

assign and_ln308_1_fu_1341_p2 = (icmp_ln309_reg_1641 & and_ln308_fu_1336_p2);

assign and_ln308_fu_1336_p2 = (xor_ln308_fu_1330_p2 & icmp_ln310_reg_1646);

assign and_ln312_fu_1420_p2 = (or_ln312_2_fu_1390_p2 & or_ln312_1_fu_1371_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_condition_862 = ((rst_n_read_read_fu_188_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (vsync_fall_fu_584_p2 == 1'd1) & (game_state_load_load_fu_560_p1 == 1'd0));
end

assign box_dx_fu_1238_p2 = ($signed(zext_ln302_fu_1150_p1) + $signed(11'd1728));

assign box_dy_fu_1248_p2 = ($signed(zext_ln290_fu_1153_p1) + $signed(11'd1808));

assign detected_read_read_fu_212_p2 = detected;

assign direction_load_load_fu_896_p1 = direction;

assign empty_fu_752_p3 = ((in_start_box_fu_714_p2[0:0] == 1'b1) ? select_ln126_fu_732_p3 : 7'd0);

assign food_on_fu_1324_p2 = (icmp_ln284_fu_1314_p2 & icmp_ln284_1_fu_1319_p2);

assign game_state_load_load_fu_560_p1 = game_state;

assign grp_fu_1046_p1 = 8'd20;

assign grp_fu_1060_p0 = {{add_ln103_reg_1532[7:3]}};

assign grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_218_2_fu_519_ap_start_reg;

assign grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_ap_start_reg;

assign grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start = grp_snake_top_Pipeline_VITIS_LOOP_71_1_fu_511_ap_start_reg;

assign hand_dx_fu_1159_p2 = (zext_ln302_fu_1150_p1 - zext_ln290_1_fu_1156_p1);

assign hand_dy_fu_1172_p2 = (zext_ln290_fu_1153_p1 - zext_ln291_fu_1169_p1);

assign hand_on_1_fu_1353_p2 = (hand_on_fu_1349_p2 & detected_read_reg_1467);

assign hand_on_fu_1349_p2 = (icmp_ln297_reg_1631 & icmp_ln297_1_reg_1636);

assign icmp_ln118_fu_696_p2 = ((abs_start_dx_fu_666_p3 < 10'd49) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_708_p2 = ((abs_start_dy_fu_688_p3 < 10'd49) ? 1'b1 : 1'b0);

assign icmp_ln126_fu_720_p2 = ((start_hold_count < 7'd120) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_760_p2 = ((empty_fu_752_p3 > 7'd118) ? 1'b1 : 1'b0);

assign icmp_ln162_fu_784_p2 = ((abs_start_dy_fu_688_p3 > abs_start_dx_fu_666_p3) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_830_p2 = ((frame_count == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_952_p2 = ((snake_row_q0 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln197_fu_931_p2 = ((snake_row_q0 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln204_fu_910_p2 = ((snake_col_q0 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln211_fu_973_p2 = ((snake_col_q0 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln228_fu_1003_p2 = ((tmp_2_fu_994_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln235_1_fu_1014_p2 = ((empty_15_reg_294 == food_row_load_reg_1513) ? 1'b1 : 1'b0);

assign icmp_ln235_fu_1009_p2 = ((empty_16_reg_306 == food_col_load_reg_1503) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_1025_p2 = ((snake_len_load_reg_1488 < 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln247_1_fu_1069_p2 = ((next_food_row_fu_1066_p1 == snake_row_q0) ? 1'b1 : 1'b0);

assign icmp_ln247_fu_1085_p2 = ((next_food_col_fu_1081_p1 == reg_541) ? 1'b1 : 1'b0);

assign icmp_ln249_fu_1096_p2 = ((next_food_col_fu_1081_p1 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln284_1_fu_1319_p2 = ((cell_row_reg_1625 == food_row_loc_3_reg_364) ? 1'b1 : 1'b0);

assign icmp_ln284_fu_1314_p2 = ((cell_col_reg_1619 == food_col_loc_3_reg_347) ? 1'b1 : 1'b0);

assign icmp_ln297_1_fu_1232_p2 = ((abs_hand_dy_fu_1218_p3 < 10'd5) ? 1'b1 : 1'b0);

assign icmp_ln297_fu_1226_p2 = ((abs_hand_dx_fu_1196_p3 < 10'd5) ? 1'b1 : 1'b0);

assign icmp_ln309_fu_1302_p2 = ((abs_box_dx_fu_1272_p3 < 10'd49) ? 1'b1 : 1'b0);

assign icmp_ln310_fu_1308_p2 = ((abs_box_dy_fu_1294_p3 < 10'd49) ? 1'b1 : 1'b0);

assign in_dead_zone_fu_778_p2 = (icmp_ln119_fu_708_p2 & icmp_ln118_fu_696_p2);

assign in_start_box_fu_714_p2 = (icmp_ln119_fu_708_p2 & and_ln117_fu_702_p2);

assign next_food_col_fu_1081_p1 = grp_fu_1046_p2[4:0];

assign next_food_row_fu_1066_p1 = urem_ln245_reg_1599[3:0];

assign not_in_start_box_fu_740_p2 = (in_start_box_fu_714_p2 ^ 1'd1);

assign or_ln312_1_fu_1371_p2 = (or_ln312_fu_1358_p2 | hand_on_1_fu_1353_p2);

assign or_ln312_2_fu_1390_p2 = (xor_ln312_fu_1385_p2 | grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_on_out);

assign or_ln312_fu_1358_p2 = (grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_on_out | food_on_reg_1651);

assign rst_n_read_read_fu_188_p2 = rst_n;

assign select_ln126_fu_732_p3 = ((icmp_ln126_fu_720_p2[0:0] == 1'b1) ? add_ln127_fu_726_p2 : start_hold_count);

assign select_ln162_fu_812_p3 = ((icmp_ln162_fu_784_p2[0:0] == 1'b1) ? select_ln171_1_fu_796_p3 : select_ln171_fu_804_p3);

assign select_ln171_1_fu_796_p3 = ((xor_ln164_fu_790_p2[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln171_fu_804_p3 = ((tmp_fu_652_p3[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign select_ln190_fu_964_p3 = ((icmp_ln190_fu_952_p2[0:0] == 1'b1) ? 4'd14 : add_ln193_fu_958_p2);

assign select_ln197_fu_943_p3 = ((icmp_ln197_fu_931_p2[0:0] == 1'b1) ? 4'd0 : add_ln200_fu_937_p2);

assign select_ln204_fu_922_p3 = ((icmp_ln204_fu_910_p2[0:0] == 1'b1) ? 5'd19 : add_ln207_fu_916_p2);

assign select_ln211_fu_985_p3 = ((icmp_ln211_fu_973_p2[0:0] == 1'b1) ? 5'd0 : add_ln214_fu_979_p2);

assign select_ln249_fu_1108_p3 = ((icmp_ln249_fu_1096_p2[0:0] == 1'b1) ? 5'd0 : add_ln252_fu_1102_p2);

assign select_ln308_fu_1396_p3 = ((and_ln308_1_reg_1657[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln312_1_fu_1403_p3 = ((or_ln312_1_fu_1371_p2[0:0] == 1'b1) ? or_ln312_fu_1358_p2 : and_ln308_1_reg_1657);

assign select_ln312_2_fu_1411_p3 = ((or_ln312_1_fu_1371_p2[0:0] == 1'b1) ? select_ln312_fu_1377_p3 : select_ln308_fu_1396_p3);

assign select_ln312_3_fu_1363_p3 = ((grp_snake_top_Pipeline_VITIS_LOOP_274_3_fu_528_snake_on_out[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln312_fu_1377_p3 = ((or_ln312_fu_1358_p2[0:0] == 1'b1) ? select_ln312_3_fu_1363_p3 : 10'd700);

assign shl_ln103_fu_600_p2 = rand_state << 8'd4;

assign snake_col_we0_out = snake_col_we0_local;

assign snake_row_we0_out = snake_row_we0_local;

assign start_dx_fu_628_p2 = ($signed(zext_ln106_fu_624_p1) + $signed(11'd1728));

assign start_dy_fu_642_p2 = ($signed(zext_ln107_fu_638_p1) + $signed(11'd1808));

assign start_hold_count_flag_0_fu_746_p2 = (not_in_start_box_fu_740_p2 | icmp_ln126_fu_720_p2);

assign storemerge_fu_1116_p3 = ((and_ln247_fu_1091_p2[0:0] == 1'b1) ? select_ln249_fu_1108_p3 : next_food_col_fu_1081_p1);

assign sub_ln109_fu_660_p2 = (10'd0 - trunc_ln106_fu_634_p1);

assign sub_ln110_fu_682_p2 = (10'd0 - trunc_ln107_fu_648_p1);

assign sub_ln293_fu_1190_p2 = (10'd0 - trunc_ln290_fu_1165_p1);

assign sub_ln294_fu_1212_p2 = (10'd0 - trunc_ln291_fu_1178_p1);

assign sub_ln304_fu_1266_p2 = (10'd0 - trunc_ln301_fu_1244_p1);

assign sub_ln305_fu_1288_p2 = (10'd0 - trunc_ln302_fu_1254_p1);

assign tmp_1_fu_674_p3 = start_dy_fu_642_p2[32'd10];

assign tmp_2_fu_994_p4 = {{snake_len_load_reg_1488[2:1]}};

assign tmp_3_fu_1182_p3 = hand_dx_fu_1159_p2[32'd10];

assign tmp_4_fu_1204_p3 = hand_dy_fu_1172_p2[32'd10];

assign tmp_5_fu_1258_p3 = box_dx_fu_1238_p2[32'd10];

assign tmp_6_fu_1280_p3 = box_dy_fu_1248_p2[32'd10];

assign tmp_fu_652_p3 = start_dx_fu_628_p2[32'd10];

assign trunc_ln106_fu_634_p1 = start_dx_fu_628_p2[9:0];

assign trunc_ln107_fu_648_p1 = start_dy_fu_642_p2[9:0];

assign trunc_ln290_fu_1165_p1 = hand_dx_fu_1159_p2[9:0];

assign trunc_ln291_fu_1178_p1 = hand_dy_fu_1172_p2[9:0];

assign trunc_ln301_fu_1244_p1 = box_dx_fu_1238_p2[9:0];

assign trunc_ln302_fu_1254_p1 = box_dy_fu_1248_p2[9:0];

assign vsync_fall_fu_584_p2 = (xor_ln97_fu_578_p2 & vsync_prev);

assign xor_ln164_fu_790_p2 = (tmp_1_fu_674_p3 ^ 1'd1);

assign xor_ln308_fu_1330_p2 = (game_state_loc_2_reg_381 ^ 1'd1);

assign xor_ln312_fu_1385_p2 = (food_on_reg_1651 ^ 1'd1);

assign xor_ln97_fu_578_p2 = (vsync ^ 1'd1);

assign zext_ln106_fu_624_p1 = coord_x;

assign zext_ln107_fu_638_p1 = coord_y;

assign zext_ln239_fu_1030_p1 = snake_len_load_reg_1488;

assign zext_ln290_1_fu_1156_p1 = coord_x_read_reg_1477;

assign zext_ln290_fu_1153_p1 = vga_y_read_reg_1455;

assign zext_ln291_fu_1169_p1 = coord_y_read_reg_1472;

assign zext_ln302_fu_1150_p1 = vga_x_read_reg_1461;

endmodule //snake_top
