// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        grid_address0,
        grid_ce0,
        grid_we0,
        grid_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] grid_address0;
output   grid_ce0;
output   grid_we0;
output  [0:0] grid_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln73_fu_86_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln75_2_fu_160_p1;
reg   [3:0] r_fu_42;
wire   [3:0] add_ln74_fu_165_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_r_load;
reg   [4:0] c_fu_46;
wire   [4:0] select_ln73_1_fu_124_p3;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [8:0] indvar_flatten_fu_50;
wire   [8:0] add_ln73_fu_92_p2;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
reg    grid_we0_local;
reg    grid_ce0_local;
wire   [0:0] icmp_ln74_fu_104_p2;
wire   [4:0] add_ln73_1_fu_118_p2;
wire   [8:0] p_shl_fu_136_p3;
wire   [8:0] zext_ln75_fu_132_p1;
wire   [3:0] select_ln73_fu_110_p3;
wire   [8:0] sub_ln75_fu_144_p2;
wire   [8:0] zext_ln75_1_fu_150_p1;
wire   [8:0] add_ln75_fu_154_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 r_fu_42 = 4'd0;
#0 c_fu_46 = 5'd0;
#0 indvar_flatten_fu_50 = 9'd0;
#0 ap_done_reg = 1'b0;
end

snake_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln73_fu_86_p2 == 1'd0)) begin
            c_fu_46 <= select_ln73_1_fu_124_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_46 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln73_fu_86_p2 == 1'd0)) begin
            indvar_flatten_fu_50 <= add_ln73_fu_92_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_50 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln73_fu_86_p2 == 1'd0)) begin
            r_fu_42 <= add_ln74_fu_165_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_42 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_fu_86_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_50;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_r_load = 4'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_42;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        grid_ce0_local = 1'b1;
    end else begin
        grid_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_fu_86_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        grid_we0_local = 1'b1;
    end else begin
        grid_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln73_1_fu_118_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln73_fu_92_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln74_fu_165_p2 = (select_ln73_fu_110_p3 + 4'd1);

assign add_ln75_fu_154_p2 = (sub_ln75_fu_144_p2 + zext_ln75_1_fu_150_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grid_address0 = zext_ln75_2_fu_160_p1;

assign grid_ce0 = grid_ce0_local;

assign grid_d0 = 1'd0;

assign grid_we0 = grid_we0_local;

assign icmp_ln73_fu_86_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd300) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_104_p2 = ((ap_sig_allocacmp_r_load == 4'd15) ? 1'b1 : 1'b0);

assign p_shl_fu_136_p3 = {{select_ln73_1_fu_124_p3}, {4'd0}};

assign select_ln73_1_fu_124_p3 = ((icmp_ln74_fu_104_p2[0:0] == 1'b1) ? add_ln73_1_fu_118_p2 : ap_sig_allocacmp_c_load);

assign select_ln73_fu_110_p3 = ((icmp_ln74_fu_104_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_r_load);

assign sub_ln75_fu_144_p2 = (p_shl_fu_136_p3 - zext_ln75_fu_132_p1);

assign zext_ln75_1_fu_150_p1 = select_ln73_fu_110_p3;

assign zext_ln75_2_fu_160_p1 = add_ln75_fu_154_p2;

assign zext_ln75_fu_132_p1 = select_ln73_1_fu_124_p3;

endmodule //snake_top_snake_top_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2
