// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snake_top_snake_top_Pipeline_VITIS_LOOP_214_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        new_len_2,
        st_body_col_address0,
        st_body_col_ce0,
        st_body_col_we0,
        st_body_col_d0,
        st_body_col_address1,
        st_body_col_ce1,
        st_body_col_q1,
        st_body_row_address0,
        st_body_row_ce0,
        st_body_row_we0,
        st_body_row_d0,
        st_body_row_address1,
        st_body_row_ce1,
        st_body_row_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [8:0] new_len_2;
output  [8:0] st_body_col_address0;
output   st_body_col_ce0;
output   st_body_col_we0;
output  [4:0] st_body_col_d0;
output  [8:0] st_body_col_address1;
output   st_body_col_ce1;
input  [4:0] st_body_col_q1;
output  [8:0] st_body_row_address0;
output   st_body_row_ce0;
output   st_body_row_we0;
output  [3:0] st_body_row_d0;
output  [8:0] st_body_row_address1;
output   st_body_row_ce1;
input  [3:0] st_body_row_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln214_fu_104_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [8:0] i_reg_145;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln215_fu_110_p2;
reg   [0:0] icmp_ln215_reg_153;
wire   [63:0] zext_ln215_fu_122_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln214_fu_133_p1;
reg   [8:0] i_3_fu_34;
wire   [8:0] i_4_fu_116_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i;
reg    st_body_col_ce1_local;
reg    st_body_col_we0_local;
reg    st_body_col_ce0_local;
reg    st_body_row_ce1_local;
reg    st_body_row_we0_local;
reg    st_body_row_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_3_fu_34 = 9'd0;
#0 ap_done_reg = 1'b0;
end

snake_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln214_fu_104_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_3_fu_34 <= i_4_fu_116_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_3_fu_34 <= 9'd299;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_145 <= ap_sig_allocacmp_i;
        icmp_ln215_reg_153 <= icmp_ln215_fu_110_p2;
    end
end

always @ (*) begin
    if (((icmp_ln214_fu_104_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 9'd299;
    end else begin
        ap_sig_allocacmp_i = i_3_fu_34;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        st_body_col_ce0_local = 1'b1;
    end else begin
        st_body_col_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        st_body_col_ce1_local = 1'b1;
    end else begin
        st_body_col_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln215_reg_153 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        st_body_col_we0_local = 1'b1;
    end else begin
        st_body_col_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        st_body_row_ce0_local = 1'b1;
    end else begin
        st_body_row_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        st_body_row_ce1_local = 1'b1;
    end else begin
        st_body_row_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln215_reg_153 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        st_body_row_we0_local = 1'b1;
    end else begin
        st_body_row_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_4_fu_116_p2 = ($signed(ap_sig_allocacmp_i) + $signed(9'd511));

assign icmp_ln214_fu_104_p2 = ((ap_sig_allocacmp_i == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_110_p2 = ((ap_sig_allocacmp_i < new_len_2) ? 1'b1 : 1'b0);

assign st_body_col_address0 = zext_ln214_fu_133_p1;

assign st_body_col_address1 = zext_ln215_fu_122_p1;

assign st_body_col_ce0 = st_body_col_ce0_local;

assign st_body_col_ce1 = st_body_col_ce1_local;

assign st_body_col_d0 = st_body_col_q1;

assign st_body_col_we0 = st_body_col_we0_local;

assign st_body_row_address0 = zext_ln214_fu_133_p1;

assign st_body_row_address1 = zext_ln215_fu_122_p1;

assign st_body_row_ce0 = st_body_row_ce0_local;

assign st_body_row_ce1 = st_body_row_ce1_local;

assign st_body_row_d0 = st_body_row_q1;

assign st_body_row_we0 = st_body_row_we0_local;

assign zext_ln214_fu_133_p1 = i_reg_145;

assign zext_ln215_fu_122_p1 = i_4_fu_116_p2;

endmodule //snake_top_snake_top_Pipeline_VITIS_LOOP_214_5
